/* This Proc Format program was automatically generated by Stat/Transfer ver.12.1.334.0516 */



libname library 'D:/benoit lepage/cours M1/formation R creation bases Stata et SAS/' ;

proc format library = library ;
   value SEXL
      0 = 'Féminin'  
      1 = 'Masculin' ;
   value TRAITL
      1 = 'Placebo'  
      2 = 'Traitement A'  
      3 = 'Traitement B' ;

proc datasets library = library ;
modify df_1_v13;
   format       sex SEXL.;
   format     trait TRAITL.;
quit;
