<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Analyse simple en R base | Formation R</title>
  <meta name="description" content="Chapter 3 Analyse simple en R base | Formation R" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Analyse simple en R base | Formation R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Chapter 3 Analyse simple en R base | Formation R" />
  <meta name="github-repo" content="formationR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Analyse simple en R base | Formation R" />
  
  <meta name="twitter:description" content="Chapter 3 Analyse simple en R base | Formation R" />
  

<meta name="author" content="Benoît Lepage" />


<meta name="date" content="2025-08-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="les-objets-dans-r.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">formationR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Bienvenue sur cette formation au logiciel R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#pourquoi-choisir-r"><i class="fa fa-check"></i><b>1.1</b> Pourquoi choisir R ?</a></li>
<li class="chapter" data-level="1.2" data-path="02-analyse_en_R_base.html"><a href="#t%C3%A9l%C3%A9chargez-le-logiciel-r"><i class="fa fa-check"></i><b>1.2</b> Téléchargez le logiciel R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#ouvrez-le-logiciel-r"><i class="fa fa-check"></i><b>1.2.1</b> Ouvrez le logiciel R</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="02-analyse_en_R_base.html"><a href="#t%C3%A9l%C3%A9chargez-un-ide-rstudio-recommand%C3%A9"><i class="fa fa-check"></i><b>1.3</b> Téléchargez un IDE (RStudio recommandé)</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#ouvrez-lide-rstudio"><i class="fa fa-check"></i><b>1.3.1</b> Ouvrez l’IDE RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#trouver-de-laide-sur-r"><i class="fa fa-check"></i><b>1.4</b> Trouver de l’aide sur R</a></li>
<li class="chapter" data-level="1.5" data-path="02-analyse_en_R_base.html"><a href="#conventions-d%C3%A9criture"><i class="fa fa-check"></i><b>1.5</b> Conventions d’écriture</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html"><i class="fa fa-check"></i><b>2</b> Les objets dans R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#manipuler-les-objets-dans-lenvironnement"><i class="fa fa-check"></i><b>2.1</b> Manipuler les objets dans l’environnement</a></li>
<li class="chapter" data-level="2.2" data-path="02-analyse_en_R_base.html"><a href="#principaux-types-de-donn%C3%A9es"><i class="fa fa-check"></i><b>2.2</b> Principaux types de données</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="02-analyse_en_R_base.html"><a href="#donn%C3%A9es-manquantes"><i class="fa fa-check"></i><b>2.2.1</b> Données manquantes</a></li>
<li class="chapter" data-level="2.2.2" data-path="02-analyse_en_R_base.html"><a href="#d%C3%A9crire-le-type-de-lobjet-spadesuit"><i class="fa fa-check"></i><b>2.2.2</b> Décrire le type de l’objet <span class="math inline">\(\spadesuit\)</span></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="02-analyse_en_R_base.html"><a href="#principales-structures-de-donn%C3%A9es"><i class="fa fa-check"></i><b>2.3</b> Principales structures de données</a></li>
<li class="chapter" data-level="2.4" data-path="02-analyse_en_R_base.html"><a href="#objet-%C3%A0-une-seule-valeur-scalaire-ou-texte"><i class="fa fa-check"></i><b>2.4</b> Objet à une seule valeur (scalaire ou texte)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#scalaires"><i class="fa fa-check"></i><b>2.4.1</b> Scalaires</a></li>
<li class="chapter" data-level="2.4.2" data-path="02-analyse_en_R_base.html"><a href="#op%C3%A9rations-math%C3%A9matiques-sur-les-scalaires"><i class="fa fa-check"></i><b>2.4.2</b> Opérations mathématiques sur les scalaires</a></li>
<li class="chapter" data-level="2.4.3" data-path="02-analyse_en_R_base.html"><a href="#concat%C3%A9nation-de-cha%C3%AEnes-de-caract%C3%A8res"><i class="fa fa-check"></i><b>2.4.3</b> Concaténation de chaînes de caractères</a></li>
<li class="chapter" data-level="2.4.4" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#valeurs-logiques-true-et-false"><i class="fa fa-check"></i><b>2.4.4</b> Valeurs logiques <code>TRUE</code> et <code>FALSE</code></a></li>
<li class="chapter" data-level="2.4.5" data-path="02-analyse_en_R_base.html"><a href="#op%C3%A9rations-sur-des-valeurs-logiques"><i class="fa fa-check"></i><b>2.4.5</b> Opérations sur des valeurs logiques</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#les-vecteurs-atomiques-c"><i class="fa fa-check"></i><b>2.5</b> Les vecteurs atomiques <code>c()</code></a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="02-analyse_en_R_base.html"><a href="#cr%C3%A9ation-dun-vecteur-atomique"><i class="fa fa-check"></i><b>2.5.1</b> Création d’un vecteur atomique</a></li>
<li class="chapter" data-level="2.5.2" data-path="02-analyse_en_R_base.html"><a href="#cr%C3%A9er-une-s%C3%A9quence-de-valeurs"><i class="fa fa-check"></i><b>2.5.2</b> Créer une séquence de valeurs</a></li>
<li class="chapter" data-level="2.5.3" data-path="02-analyse_en_R_base.html"><a href="#cr%C3%A9er-un-vecteur-de-valeurs-r%C3%A9p%C3%A9t%C3%A9es"><i class="fa fa-check"></i><b>2.5.3</b> Créer un vecteur de valeurs répétées</a></li>
<li class="chapter" data-level="2.5.4" data-path="02-analyse_en_R_base.html"><a href="#op%C3%A9rations-arithm%C3%A9tiques-sur-un-vecteur"><i class="fa fa-check"></i><b>2.5.4</b> Opérations arithmétiques sur un vecteur</a></li>
<li class="chapter" data-level="2.5.5" data-path="02-analyse_en_R_base.html"><a href="#op%C3%A9rations-logiques-sur-un-vecteur"><i class="fa fa-check"></i><b>2.5.5</b> Opérations logiques sur un vecteur</a></li>
<li class="chapter" data-level="2.5.6" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#principe-de-coercition"><i class="fa fa-check"></i><b>2.5.6</b> Principe de coercition</a></li>
<li class="chapter" data-level="2.5.7" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#attributs-dun-vecteur"><i class="fa fa-check"></i><b>2.5.7</b> Attributs d’un vecteur</a></li>
<li class="chapter" data-level="2.5.8" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#vecteurs-de-type-factor"><i class="fa fa-check"></i><b>2.5.8</b> Vecteurs de type <code>factor</code></a></li>
<li class="chapter" data-level="2.5.9" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#vecteurs-de-type-date-ou-date-time"><i class="fa fa-check"></i><b>2.5.9</b> Vecteurs de type <code>Date</code> ou <code>Date-time</code></a></li>
<li class="chapter" data-level="2.5.10" data-path="02-analyse_en_R_base.html"><a href="#s%C3%A9lection-par-indexation"><i class="fa fa-check"></i><b>2.5.10</b> Sélection par indexation</a></li>
<li class="chapter" data-level="2.5.11" data-path="02-analyse_en_R_base.html"><a href="#fonctions-statistiques-pour-r%C3%A9sumer-une-s%C3%A9rie-de-valeurs"><i class="fa fa-check"></i><b>2.5.11</b> Fonctions statistiques pour résumer une série de valeurs</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#les-listes-list"><i class="fa fa-check"></i><b>2.6</b> Les listes <code>list()</code></a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="02-analyse_en_R_base.html"><a href="#cr%C3%A9ation-dune-liste"><i class="fa fa-check"></i><b>2.6.1</b> Création d’une liste</a></li>
<li class="chapter" data-level="2.6.2" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#attributs-dune-liste"><i class="fa fa-check"></i><b>2.6.2</b> Attributs d’une liste</a></li>
<li class="chapter" data-level="2.6.3" data-path="02-analyse_en_R_base.html"><a href="#indexation-des-%C3%A9l%C3%A9ments-dune-liste"><i class="fa fa-check"></i><b>2.6.3</b> Indexation des éléments d’une liste</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#les-matrices-matrix"><i class="fa fa-check"></i><b>2.7</b> Les matrices <code>matrix()</code></a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="02-analyse_en_R_base.html"><a href="#cr%C3%A9ation-dune-matrice"><i class="fa fa-check"></i><b>2.7.1</b> Création d’une matrice</a></li>
<li class="chapter" data-level="2.7.2" data-path="02-analyse_en_R_base.html"><a href="#s%C3%A9lection-par-indexation-au-sein-dune-matrice"><i class="fa fa-check"></i><b>2.7.2</b> Sélection par indexation au sein d’une matrice</a></li>
<li class="chapter" data-level="2.7.3" data-path="les-objets-dans-r.html"><a href="les-objets-dans-r.html#collection-de-plusieurs-matrices-array-spadesuit"><i class="fa fa-check"></i><b>2.7.3</b> Collection de plusieurs matrices, <code>array()</code> <span class="math inline">\(\spadesuit\)</span></a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="02-analyse_en_R_base.html"><a href="#les-bases-de-donn%C3%A9es-data.frame"><i class="fa fa-check"></i><b>2.8</b> Les bases de données <code>data.frame()</code></a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="02-analyse_en_R_base.html"><a href="#cr%C3%A9ation-dun-data-frame"><i class="fa fa-check"></i><b>2.8.1</b> Création d’un <em>data frame</em></a></li>
<li class="chapter" data-level="2.8.2" data-path="02-analyse_en_R_base.html"><a href="#s%C3%A9lection-par-indexation-1"><i class="fa fa-check"></i><b>2.8.2</b> Sélection par indexation</a></li>
<li class="chapter" data-level="2.8.3" data-path="02-analyse_en_R_base.html"><a href="#autres-formats-de-bases-de-donn%C3%A9es"><i class="fa fa-check"></i><b>2.8.3</b> Autres formats de bases de données</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html"><i class="fa fa-check"></i><b>3</b> Analyse simple en R base</a>
<ul>
<li class="chapter" data-level="3.1" data-path="02-analyse_en_R_base.html"><a href="#pr%C3%A9parer-un-dossier-de-travail"><i class="fa fa-check"></i><b>3.1</b> Préparer un dossier de travail</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#projet-r"><i class="fa fa-check"></i><b>3.1.1</b> Projet R</a></li>
<li class="chapter" data-level="3.1.2" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#structurer-un-script-danalyse"><i class="fa fa-check"></i><b>3.1.2</b> Structurer un script d’analyse</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="02-analyse_en_R_base.html"><a href="#importer-une-base-de-donn%C3%A9es"><i class="fa fa-check"></i><b>3.2</b> Importer une base de données</a></li>
<li class="chapter" data-level="3.3" data-path="02-analyse_en_R_base.html"><a href="#examiner-les-donn%C3%A9es-et-les-m%C3%A9ta-donn%C3%A9es"><i class="fa fa-check"></i><b>3.3</b> Examiner les données et les méta-données</a></li>
<li class="chapter" data-level="3.4" data-path="02-analyse_en_R_base.html"><a href="#cr%C3%A9er-ou-modifier-une-variable"><i class="fa fa-check"></i><b>3.4</b> Créer ou modifier une variable</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="02-analyse_en_R_base.html"><a href="#cr%C3%A9er-des-variables"><i class="fa fa-check"></i><b>3.4.1</b> Créer des variables</a></li>
<li class="chapter" data-level="3.4.2" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#modifier-des-variables"><i class="fa fa-check"></i><b>3.4.2</b> Modifier des variables</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="02-analyse_en_R_base.html"><a href="#analyses-univari%C3%A9es"><i class="fa fa-check"></i><b>3.5</b> Analyses univariées</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#fonction-summary"><i class="fa fa-check"></i><b>3.5.1</b> fonction <code>summary()</code></a></li>
<li class="chapter" data-level="3.5.2" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#variables-quantitatives-1"><i class="fa fa-check"></i><b>3.5.2</b> Variables quantitatives</a></li>
<li class="chapter" data-level="3.5.3" data-path="02-analyse_en_R_base.html"><a href="#programmation-%C3%A9l%C3%A9mentaire"><i class="fa fa-check"></i><b>3.5.3</b> Programmation élémentaire</a></li>
<li class="chapter" data-level="3.5.4" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#variables-qualitatives-1"><i class="fa fa-check"></i><b>3.5.4</b> Variables qualitatives</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="02-analyse_en_R_base.html"><a href="#repr%C3%A9sentations-graphiques"><i class="fa fa-check"></i><b>3.6</b> Représentations graphiques</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="02-analyse_en_R_base.html"><a href="#distributions-univari%C3%A9es"><i class="fa fa-check"></i><b>3.6.1</b> Distributions univariées</a></li>
<li class="chapter" data-level="3.6.2" data-path="02-analyse_en_R_base.html"><a href="#distributions-bivari%C3%A9es"><i class="fa fa-check"></i><b>3.6.2</b> Distributions bivariées</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="02-analyse_en_R_base.html"><a href="#analyses-bivari%C3%A9es"><i class="fa fa-check"></i><b>3.7</b> Analyses bivariées</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#variable-quantitative-times-qualitative"><i class="fa fa-check"></i><b>3.7.1</b> Variable quantitative <span class="math inline">\(\times\)</span> qualitative</a></li>
<li class="chapter" data-level="3.7.2" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#variable-qualitative-times-qualitative"><i class="fa fa-check"></i><b>3.7.2</b> Variable qualitative <span class="math inline">\(\times\)</span> qualitative</a></li>
<li class="chapter" data-level="3.7.3" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#comparer-2-moyennes"><i class="fa fa-check"></i><b>3.7.3</b> Comparer 2 moyennes</a></li>
<li class="chapter" data-level="3.7.4" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#comparer-3-moyennes-ou-plus"><i class="fa fa-check"></i><b>3.7.4</b> Comparer 3 moyennes ou plus</a></li>
<li class="chapter" data-level="3.7.5" data-path="analyse-simple-en-r-base.html"><a href="analyse-simple-en-r-base.html#comparer-des-pourcentages"><i class="fa fa-check"></i><b>3.7.5</b> Comparer des pourcentages</a></li>
<li class="chapter" data-level="3.7.6" data-path="02-analyse_en_R_base.html"><a href="#corr%C3%A9lations"><i class="fa fa-check"></i><b>3.7.6</b> Corrélations</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="02-analyse_en_R_base.html"><a href="#analyse-multivari%C3%A9e"><i class="fa fa-check"></i><b>3.8</b> Analyse multivariée</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Formation R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analyse-simple-en-r-base" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Analyse simple en R base<a href="analyse-simple-en-r-base.html#analyse-simple-en-r-base" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Dans ce chapitre, nous allons analyser une base de données simple en utilisant les commandes de R base.</p>
<p>Les objectifs de ce chapitre sont de :</p>
<ul>
<li><strong>préparer un dossier (et un environnement) de travail</strong> pour réaliser les analyses</li>
<li><strong>importer des données</strong>, <strong>créer des variables</strong>, <strong>modifier une variable déjà existante</strong></li>
<li>réaliser des <strong>analyses descriptives univariées</strong> des variables quantitatives et qualitatives</li>
<li>réaliser des <strong>analyses descriptives bivariées</strong></li>
<li>faire des <strong>représentations graphiques</strong> des données</li>
<li>savoir faire les <strong>tests statistiques de comparaison</strong> de moyennes et de pourcentages</li>
<li>savoir faire une <strong>modèle de régression linéaire multivariée</strong>, et vérifier ses conditions d’application</li>
<li><strong>sauvegarder</strong> les données et les résultats</li>
</ul>
<p><em>Note : Nous verrons dans les chapitre suivants comment réaliser la même analyse en utilisant : </em></p>
<ul>
<li><em>des packages spécifiques qui facilitent la réalisation et la présentation des analyses.</em></li>
<li><em>la collection de packages du <code>tidyverse</code> qui apportent de nouvelles fonctions avec une nouvelle philosophie, une nouvelle grammaire et de nouvelles structures de données, qui est très utilisé dans la communauté des utilisateurs de R.</em></li>
</ul>
<div id="préparer-un-dossier-de-travail" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Préparer un dossier de travail<a href="#pr%C3%A9parer-un-dossier-de-travail" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="projet-r" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Projet R<a href="analyse-simple-en-r-base.html#projet-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>1ère étape : Créer un dossier de travail.</strong> Commencez par créer un dossier vide, appelé <em>analyse R base</em> dans l’endroit de votre choix sur votre ordinateur. Au sein de ce dossier, vous pouvez ajouter un dossier <em>data</em> et un dossier <em>figures</em> qui pourra vous servir à stocker les données et les figures que vous souhaitez souvegarder.</p>
<p><strong>2ème étape : Créer un projet R.</strong> Dans R Studio, cliquez sur le cube en 3 dimensions R “Project: (None)” en haut à droite, au dessus du cadran environnement.</p>
<ul>
<li>puis “New Project…”.</li>
<li>choisissez “Existing Directory…”. Avec le bouton browse, vous pouvez alors rechercher le dossier <em>analyse R base</em> que vous venez de créer à la 1ère étape.</li>
<li>enfin cliquez sur “Open” et “Create Project”.
<img src="images/cree_nv_project.jpg" width="100%" style="display: block; margin: auto;" /></li>
</ul>
<!-- , fig.cap="Créer un nouveau projet" -->
<p>R Studio va alors créer un fichier <code>analyse R base.Rproj</code> au sein de votre dossier <em>analyse R base</em>. De plus, ce dossier <em>analyse R base</em> sera défini comme votre dossier de travail au sein de R Studio.</p>
<p>Ainsi si vous demandez à R quel est votre dossier de travail actuel avec la commande <code>getwd()</code> (<em>get working directory</em>), la console va indiquer le chemin jusque ce dossier (R vous confirme qu’il s’agit bien de votre dossier de travail !).</p>
<p>Le contenu de ce dossier de travail apparaît également dans le menu “Files” dans le cadrant en bas à droite. Ce dossier sert de “dossier racine” (“répertoire racine”). Les fichiers au sein de ce dossier pourront être désignés avec un chemin raccourci. <strong>Tous les éléments que vous allez sauvegarder pendant votre session R Studio seront sauvegardés dans ce dossier de travail +++</strong>
<img src="images/working_directory.jpg" width="75%" style="display: block; margin: auto;" />
<!-- , fig.cap="Dossier de travail" -->
Si vous ouvrez un nouveau script R et que vous le sauvegardez (par exemple, sous le nom <code>1_analyse en R base</code>), il sera ajouté par défaut au sein de votre dossier de travail, et va apparaître parmi les fichiers du menu file (cadrant en bas à droite).</p>
<p>Maintenant, <strong>quittez le programme R Studio</strong>, puis <strong>double cliquez sur le fichier <code>analyse R base.Rproj</code></strong> (icone d’un cube R en 3 dimensions) qui vient d’être créé dans votre dossier de travail “analyse R base”.</p>
<p>R Studio va alors s’ouvrir, en ayant directement défini le dossier <em>analyse R base</em> comme dossier de travail. C’est la méthode la plus simple pour reprendre une analyse R en cours et pour reproduire les résultats déjà obtenus.</p>
</div>
<div id="structurer-un-script-danalyse" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Structurer un script d’analyse<a href="analyse-simple-en-r-base.html#structurer-un-script-danalyse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Lorsque vous réaliserez une analyse, vous allez <strong>sauvegarder vos commandes dans un script</strong> (par exemple, dans le script <code>1_analyse en R base.R</code> que l’on vient de sauvegarder précédemment).</p>
<p>En haut du script, si vous souhaitez recommencer à partir d’un environnement vide lorsque vous relancerez l’analyse depuis le départ, vous pouvez ajouter la commande <code>rm(ls = list())</code>.</p>
<p>Une bonne pratique est d’indiquer quelques informations utiles pour documenter votre script, comme votre <strong>nom et la date des analyses (en commentaires)</strong>. Enfin, à la fin d’un script (à la fin de vos analyses), vous pouvez lancer la commande <code>sessionInfo()</code> qui va lister dans la console la version de R et les versions des packages qui ont été utilisés pour votre analyse (vous pourrez copier ces informations à la fin de votre script, en commentaires).</p>
<p>Les commentaires peuvent également servir à indiquer des <strong>titres</strong> et <strong>sous-titres</strong> dans votre script d’analyse. Un menu d’accès rapide est alors accessible à partir du bouton <em>Outline</em> en haut à droite de la fenêtre du script R.</p>
<p><em>Note : sur windows, le raccourci “ctrl-shift-c” transforme les lignes sélectionnées en commentaires (en ajoutant automatiquement des <code>#</code> en début de ligne)</em></p>
<p>Voici un exemple de script qui suit cette structure :</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="analyse-simple-en-r-base.html#cb75-1" tabindex="-1"></a><span class="do">### 1_analyse en R base</span></span>
<span id="cb75-2"><a href="analyse-simple-en-r-base.html#cb75-2" tabindex="-1"></a><span class="do">### Date : 15 septembre 2025 </span></span>
<span id="cb75-3"><a href="analyse-simple-en-r-base.html#cb75-3" tabindex="-1"></a><span class="do">### Auteur : Timoté Chalamais</span></span>
<span id="cb75-4"><a href="analyse-simple-en-r-base.html#cb75-4" tabindex="-1"></a></span>
<span id="cb75-5"><a href="analyse-simple-en-r-base.html#cb75-5" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># cette commande vide le contenu de l&#39;environnement</span></span>
<span id="cb75-6"><a href="analyse-simple-en-r-base.html#cb75-6" tabindex="-1"></a></span>
<span id="cb75-7"><a href="analyse-simple-en-r-base.html#cb75-7" tabindex="-1"></a><span class="co"># ---------------------------------------------------------------------------- #</span></span>
<span id="cb75-8"><a href="analyse-simple-en-r-base.html#cb75-8" tabindex="-1"></a><span class="co"># 1) Titre n°1 (il faut ajouter 4 tirets à la fin des titres) ----</span></span>
<span id="cb75-9"><a href="analyse-simple-en-r-base.html#cb75-9" tabindex="-1"></a><span class="do">## 1.2) Sous-titre (en ajoutant un # au début de ligne) ----</span></span>
<span id="cb75-10"><a href="analyse-simple-en-r-base.html#cb75-10" tabindex="-1"></a><span class="do">### 1.2.1) Sous-sous-titre (en ajoutant des # supplémentaires) ---- </span></span>
<span id="cb75-11"><a href="analyse-simple-en-r-base.html#cb75-11" tabindex="-1"></a><span class="co"># ---------------------------------------------------------------------------- #</span></span>
<span id="cb75-12"><a href="analyse-simple-en-r-base.html#cb75-12" tabindex="-1"></a></span>
<span id="cb75-13"><a href="analyse-simple-en-r-base.html#cb75-13" tabindex="-1"></a><span class="co"># Import des données</span></span>
<span id="cb75-14"><a href="analyse-simple-en-r-base.html#cb75-14" tabindex="-1"></a>df_1 <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/df_1.csv&quot;</span>)</span>
<span id="cb75-15"><a href="analyse-simple-en-r-base.html#cb75-15" tabindex="-1"></a>meta_df_1 <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/meta_df_1.csv&quot;</span>)</span>
<span id="cb75-16"><a href="analyse-simple-en-r-base.html#cb75-16" tabindex="-1"></a></span>
<span id="cb75-17"><a href="analyse-simple-en-r-base.html#cb75-17" tabindex="-1"></a><span class="co"># ---------------------------------------------------------------------------- #</span></span>
<span id="cb75-18"><a href="analyse-simple-en-r-base.html#cb75-18" tabindex="-1"></a><span class="co"># 2) Titre n°2  ----</span></span>
<span id="cb75-19"><a href="analyse-simple-en-r-base.html#cb75-19" tabindex="-1"></a><span class="co"># ---------------------------------------------------------------------------- #</span></span>
<span id="cb75-20"><a href="analyse-simple-en-r-base.html#cb75-20" tabindex="-1"></a><span class="fu">head</span>(df_1)</span>
<span id="cb75-21"><a href="analyse-simple-en-r-base.html#cb75-21" tabindex="-1"></a></span>
<span id="cb75-22"><a href="analyse-simple-en-r-base.html#cb75-22" tabindex="-1"></a>(...) <span class="co"># continuez vous analyses</span></span>
<span id="cb75-23"><a href="analyse-simple-en-r-base.html#cb75-23" tabindex="-1"></a>(...)</span>
<span id="cb75-24"><a href="analyse-simple-en-r-base.html#cb75-24" tabindex="-1"></a></span>
<span id="cb75-25"><a href="analyse-simple-en-r-base.html#cb75-25" tabindex="-1"></a><span class="co"># ---------------------------------------------------------------------------- #</span></span>
<span id="cb75-26"><a href="analyse-simple-en-r-base.html#cb75-26" tabindex="-1"></a><span class="co"># Fin de script  ----</span></span>
<span id="cb75-27"><a href="analyse-simple-en-r-base.html#cb75-27" tabindex="-1"></a></span>
<span id="cb75-28"><a href="analyse-simple-en-r-base.html#cb75-28" tabindex="-1"></a><span class="co"># à la fin, vous pouvez récupérer les informations sur la session </span></span>
<span id="cb75-29"><a href="analyse-simple-en-r-base.html#cb75-29" tabindex="-1"></a><span class="co"># pour les copier-coller en bas du script (en format de commentaires)</span></span>
<span id="cb75-30"><a href="analyse-simple-en-r-base.html#cb75-30" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span>
<span id="cb75-31"><a href="analyse-simple-en-r-base.html#cb75-31" tabindex="-1"></a><span class="co"># R version 4.5.1 (2025-06-13 ucrt)</span></span>
<span id="cb75-32"><a href="analyse-simple-en-r-base.html#cb75-32" tabindex="-1"></a><span class="co"># Platform: x86_64-w64-mingw32/x64</span></span>
<span id="cb75-33"><a href="analyse-simple-en-r-base.html#cb75-33" tabindex="-1"></a><span class="co"># Running under: Windows 11 x64 (build 26100)</span></span>
<span id="cb75-34"><a href="analyse-simple-en-r-base.html#cb75-34" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb75-35"><a href="analyse-simple-en-r-base.html#cb75-35" tabindex="-1"></a><span class="co"># Matrix products: default</span></span>
<span id="cb75-36"><a href="analyse-simple-en-r-base.html#cb75-36" tabindex="-1"></a><span class="co">#   LAPACK version 3.12.1</span></span>
<span id="cb75-37"><a href="analyse-simple-en-r-base.html#cb75-37" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb75-38"><a href="analyse-simple-en-r-base.html#cb75-38" tabindex="-1"></a><span class="co"># locale:</span></span>
<span id="cb75-39"><a href="analyse-simple-en-r-base.html#cb75-39" tabindex="-1"></a><span class="co"># [1] LC_COLLATE=French_France.utf8 </span></span>
<span id="cb75-40"><a href="analyse-simple-en-r-base.html#cb75-40" tabindex="-1"></a><span class="co"># [2] LC_CTYPE=French_France.utf8   </span></span>
<span id="cb75-41"><a href="analyse-simple-en-r-base.html#cb75-41" tabindex="-1"></a><span class="co"># [3] LC_MONETARY=French_France.utf8</span></span>
<span id="cb75-42"><a href="analyse-simple-en-r-base.html#cb75-42" tabindex="-1"></a><span class="co"># [4] LC_NUMERIC=C                  </span></span>
<span id="cb75-43"><a href="analyse-simple-en-r-base.html#cb75-43" tabindex="-1"></a><span class="co"># [5] LC_TIME=French_France.utf8    </span></span>
<span id="cb75-44"><a href="analyse-simple-en-r-base.html#cb75-44" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb75-45"><a href="analyse-simple-en-r-base.html#cb75-45" tabindex="-1"></a><span class="co"># time zone: Europe/Paris</span></span>
<span id="cb75-46"><a href="analyse-simple-en-r-base.html#cb75-46" tabindex="-1"></a><span class="co"># tzcode source: internal</span></span>
<span id="cb75-47"><a href="analyse-simple-en-r-base.html#cb75-47" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb75-48"><a href="analyse-simple-en-r-base.html#cb75-48" tabindex="-1"></a><span class="co"># attached base packages:</span></span>
<span id="cb75-49"><a href="analyse-simple-en-r-base.html#cb75-49" tabindex="-1"></a><span class="co"># [1] stats     graphics  grDevices utils     datasets </span></span>
<span id="cb75-50"><a href="analyse-simple-en-r-base.html#cb75-50" tabindex="-1"></a><span class="co"># [6] methods   base     </span></span>
<span id="cb75-51"><a href="analyse-simple-en-r-base.html#cb75-51" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb75-52"><a href="analyse-simple-en-r-base.html#cb75-52" tabindex="-1"></a><span class="co"># loaded via a namespace (and not attached):</span></span>
<span id="cb75-53"><a href="analyse-simple-en-r-base.html#cb75-53" tabindex="-1"></a><span class="co">#  [1] compiler_4.5.1    bookdown_0.43    </span></span>
<span id="cb75-54"><a href="analyse-simple-en-r-base.html#cb75-54" tabindex="-1"></a><span class="co">#  [3] fastmap_1.2.0     cli_3.6.5        </span></span>
<span id="cb75-55"><a href="analyse-simple-en-r-base.html#cb75-55" tabindex="-1"></a><span class="co">#  [5] htmltools_0.5.8.1 tools_4.5.1      </span></span>
<span id="cb75-56"><a href="analyse-simple-en-r-base.html#cb75-56" tabindex="-1"></a><span class="co">#  [7] rstudioapi_0.17.1 yaml_2.3.10      </span></span>
<span id="cb75-57"><a href="analyse-simple-en-r-base.html#cb75-57" tabindex="-1"></a><span class="co">#  [9] rmarkdown_2.29    knitr_1.50       </span></span>
<span id="cb75-58"><a href="analyse-simple-en-r-base.html#cb75-58" tabindex="-1"></a><span class="co"># [11] xfun_0.52         digest_0.6.37    </span></span>
<span id="cb75-59"><a href="analyse-simple-en-r-base.html#cb75-59" tabindex="-1"></a><span class="co"># [13] rlang_1.1.6       evaluate_1.0.4 </span></span></code></pre></div>
</div>
</div>
<div id="importer-une-base-de-données" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Importer une base de données<a href="#importer-une-base-de-donn%C3%A9es" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Pour cet exemple,</p>
<ul>
<li>téléchargez la base <a href="https://github.com/benoitlepage/formationR/blob/main/data/df_1.csv"><code>df_1.csv</code></a> ainsi que la base de méta-données <a href="https://github.com/benoitlepage/formationR/blob/main/data/meta_df_1.csv"><code>meta_df_1.csv</code></a> (cliquez sur le bouton <em>download raw file</em>, à droite avec une flèche vers le bas).</li>
<li>Vous pouvez ensuite coller ces deux bases de données au sein du dossier <em>data</em> de votre dossier de travail.</li>
</ul>
<p>Il s’agit de fichiers avec l’extension “.csv” (<em>comma separated variables</em>) où les valeurs sont séparées par un point virgule. Vous pouvez les importer dans R avec la fonction <code>read.csv2()</code> (il existe également une fonction <code>read.csv()</code> qui importe les données .csv où le séparateur est une virgule). Vous pouvez regarder les différents arguments de ces fonctions dans l’aide <code>?read.csv2</code>.</p>
<p>Nous allons stocker la base dans des objets nommés <code>df_1</code> et <code>meta_df_1</code>. Ces bases importées sont des objets de type <code>data.frame</code>.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="analyse-simple-en-r-base.html#cb76-1" tabindex="-1"></a>df_1 <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/df_1.csv&quot;</span>)</span>
<span id="cb76-2"><a href="analyse-simple-en-r-base.html#cb76-2" tabindex="-1"></a>meta_df_1 <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/meta_df_1.csv&quot;</span>)</span>
<span id="cb76-3"><a href="analyse-simple-en-r-base.html#cb76-3" tabindex="-1"></a><span class="fu">class</span>(df_1)  <span class="co"># [1] &quot;data.frame&quot;</span></span></code></pre></div>
<ul>
<li>La base <code>df_1</code> contient les données que nous allons analyser.</li>
<li>La base <code>meta_df_1</code> contient des méta-données (noms de variables, noms des labels, etc) qui sera utile pour préciser les noms des variables, les labels des variables qualitatives, etc.</li>
</ul>
</div>
<div id="examiner-les-données-et-les-méta-données" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Examiner les données et les méta-données<a href="#examiner-les-donn%C3%A9es-et-les-m%C3%A9ta-donn%C3%A9es" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Comme vu précédemment, vous pouvez examiner les données avec les fonctions <code>head()</code>, <code>tail()</code>, <code>str()</code> et <code>View()</code>.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="analyse-simple-en-r-base.html#cb77-1" tabindex="-1"></a><span class="fu">head</span>(df_1)</span></code></pre></div>
<pre><code>##   subjid sex  imc trait pas
## 1      1   0 24.8     2 140
## 2      2   0 24.1     3 109
## 3      3   0 26.4     1 156
## 4      4   0 23.3     2 124
## 5      5   0 25.4     2 131
## 6      6   1 25.0     3 148</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="analyse-simple-en-r-base.html#cb79-1" tabindex="-1"></a><span class="fu">tail</span>(df_1)</span></code></pre></div>
<pre><code>##     subjid sex  imc trait pas
## 295    295   1 24.1     1 148
## 296    296   0 18.7     3 121
## 297    297   0 23.3     3 111
## 298    298   1 27.5     3 134
## 299    299   1 24.7     2 158
## 300    300   1 22.8     1 147</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="analyse-simple-en-r-base.html#cb81-1" tabindex="-1"></a><span class="fu">str</span>(df_1)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    300 obs. of  5 variables:
##  $ subjid: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ sex   : int  0 0 0 0 0 1 0 0 0 0 ...
##  $ imc   : num  24.8 24.1 26.4 23.3 25.4 25 25.2 21.5 21.8 25.9 ...
##  $ trait : int  2 3 1 2 2 3 3 3 1 1 ...
##  $ pas   : int  140 109 156 124 131 148 125 117 132 133 ...</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="analyse-simple-en-r-base.html#cb83-1" tabindex="-1"></a><span class="fu">View</span>(df_1) <span class="co"># pour voir la base de données dans R Studio</span></span></code></pre></div>
<p>On voit que la base de données contient 300 observations et 5 variables :</p>
<ul>
<li><code>subjid</code>, l’identifiant patient</li>
<li><code>sex</code>, le sexe du patient</li>
<li><code>imc</code>, l’indice de masse corporelle du patient (en kg/m2)</li>
<li><code>trait</code>, le traitement 0 = placebo, 1 = traitement A, 2 = traitement B</li>
<li><code>pas</code>, la pression artérielle systolique (en mmHg)</li>
</ul>
<p>Toutes les variables dans <code>df_1</code> sont de type entier (<code>int</code>) ou réel (<code>num</code>).</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="analyse-simple-en-r-base.html#cb84-1" tabindex="-1"></a>meta_df_1 <span class="co"># pour regarder le contenu des méta-données : </span></span></code></pre></div>
<pre><code>##      var               label id_labs code_labs         labs
## 1 subjid Identifiant patient       1        NA             
## 2    sex                Sexe       1         0      Féminin
## 3    sex                Sexe       2         1     Masculin
## 4    imc         IMC (kg/m²)       1        NA             
## 5  trait          Traitement       1         1      Placebo
## 6  trait          Traitement       2         2 Traitement A
## 7  trait          Traitement       3         3 Traitement B
## 8    pas          PAS (mmHg)       1        NA</code></pre>
<p>La base de méta-données contient 5 variables :</p>
<ul>
<li><code>var</code>, nom des variables que l’on retrouve dans la base de données <code>df_1</code></li>
<li><code>label</code>, nom en détail de la variable<br />
</li>
<li><code>id_labs</code>, un identifiant pour les labels éventuels, par variable</li>
<li><code>code_labs</code>, codage numérique du label (code utilisé dans la base <code>df_1</code>)</li>
<li><code>labs</code>, modalités de réponses des variables qualitatives, en détail</li>
</ul>
</div>
<div id="créer-ou-modifier-une-variable" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Créer ou modifier une variable<a href="#cr%C3%A9er-ou-modifier-une-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="créer-des-variables" class="section level3 hasAnchor" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Créer des variables<a href="#cr%C3%A9er-des-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nous allons créer une variable <code>obesite</code> dont la valeur est égale à 1 si l’indice de masse corporelle est <span class="math inline">\(\geq 30\text{ kg/m}^2\)</span> et égale à 0 sinon.</p>
<p>Pour cela, on peut utilise la fonction <code>ifelse()</code> dont le premier argument est une condition, le 2ème argument est la valeur à retourner si la condition est vraie, et le 3ème argument est la valeur à retourner si la condition est fausse.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="analyse-simple-en-r-base.html#cb86-1" tabindex="-1"></a>df_1<span class="sc">$</span>obesite <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df_1<span class="sc">$</span>imc <span class="sc">&gt;=</span> <span class="dv">30</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code></pre></div>
<p>Chaque fois que vous créez ou modifiez une variable, il est utile de vérifier que vous n’avez pas fait d’erreurs. Dans cet exemple, on peut vérifier quelles sont les valeurs minimales et maximales de l’indice de masse corporelle au sein des deux catégories de la nouvelle variable :</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="analyse-simple-en-r-base.html#cb87-1" tabindex="-1"></a><span class="do">### vérifier que la variable est correctement crée : </span></span>
<span id="cb87-2"><a href="analyse-simple-en-r-base.html#cb87-2" tabindex="-1"></a><span class="fu">min</span>(df_1<span class="sc">$</span>imc[df_1<span class="sc">$</span>obesite <span class="sc">==</span> <span class="dv">0</span>]) <span class="co"># [1] 15.4</span></span>
<span id="cb87-3"><a href="analyse-simple-en-r-base.html#cb87-3" tabindex="-1"></a><span class="fu">max</span>(df_1<span class="sc">$</span>imc[df_1<span class="sc">$</span>obesite <span class="sc">==</span> <span class="dv">0</span>]) <span class="co"># [1] 29.9</span></span>
<span id="cb87-4"><a href="analyse-simple-en-r-base.html#cb87-4" tabindex="-1"></a><span class="do">### les valeurs d&#39;IMC varient de 15.4 à 29.9 lorsque obesite == 0</span></span>
<span id="cb87-5"><a href="analyse-simple-en-r-base.html#cb87-5" tabindex="-1"></a></span>
<span id="cb87-6"><a href="analyse-simple-en-r-base.html#cb87-6" tabindex="-1"></a><span class="fu">min</span>(df_1<span class="sc">$</span>imc[df_1<span class="sc">$</span>obesite <span class="sc">==</span> <span class="dv">1</span>]) <span class="co"># [1] 30.1</span></span>
<span id="cb87-7"><a href="analyse-simple-en-r-base.html#cb87-7" tabindex="-1"></a><span class="fu">max</span>(df_1<span class="sc">$</span>imc[df_1<span class="sc">$</span>obesite <span class="sc">==</span> <span class="dv">1</span>]) <span class="co"># [1] 32.5</span></span>
<span id="cb87-8"><a href="analyse-simple-en-r-base.html#cb87-8" tabindex="-1"></a><span class="do">### les valeurs d&#39;IMC varient de 30.1 à 32.5 lorsque obesite == 1 =&gt; c&#39;est bon !</span></span></code></pre></div>
<p>Nous allons ensuite créer une variable d’IMC en classes (<code>imc_cl</code>) définie telle que :</p>
<ul>
<li><code>imc_cl = 1</code> (maigreur) si l’IMC &lt; 18.5 kg/m<span class="math inline">\(^2\)</span>,</li>
<li><code>imc_cl = 2</code> (normal) si l’IMC <span class="math inline">\(\geq 18.5 \text{ kg/m}^2\)</span> et IMC <span class="math inline">\(&lt; 25 \text{ kg/m}^2\)</span>,</li>
<li><code>imc_cl = 3</code> (normal) si l’IMC <span class="math inline">\(\geq 25 \text{ kg/m}^2\)</span> et IMC <span class="math inline">\(&lt; 30 \text{ kg/m}^2\)</span>,</li>
<li><code>imc_cl = 4</code> (normal) si l’IMC <span class="math inline">\(\geq 30 \text{ kg/m}^2\)</span>.</li>
</ul>
<p>Il y a plusieurs possibilités pour créer cette variable, voici 3 méthodes différentes :</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="analyse-simple-en-r-base.html#cb88-1" tabindex="-1"></a><span class="do">### 1) créer une variable où toutes les données sont manquantes : </span></span>
<span id="cb88-2"><a href="analyse-simple-en-r-base.html#cb88-2" tabindex="-1"></a>df_1<span class="sc">$</span>imc_cl <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(df_1))</span>
<span id="cb88-3"><a href="analyse-simple-en-r-base.html#cb88-3" tabindex="-1"></a><span class="do">###    puis remplacer les données manquantes par les valeurs souhaitées</span></span>
<span id="cb88-4"><a href="analyse-simple-en-r-base.html#cb88-4" tabindex="-1"></a>df_1<span class="sc">$</span>imc_cl[df_1<span class="sc">$</span>imc <span class="sc">&lt;</span> <span class="fl">18.5</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb88-5"><a href="analyse-simple-en-r-base.html#cb88-5" tabindex="-1"></a>df_1<span class="sc">$</span>imc_cl[df_1<span class="sc">$</span>imc <span class="sc">&gt;=</span> <span class="fl">18.5</span> <span class="sc">&amp;</span> df_1<span class="sc">$</span>imc <span class="sc">&lt;</span> <span class="dv">25</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb88-6"><a href="analyse-simple-en-r-base.html#cb88-6" tabindex="-1"></a>df_1<span class="sc">$</span>imc_cl[df_1<span class="sc">$</span>imc <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> df_1<span class="sc">$</span>imc <span class="sc">&lt;</span> <span class="dv">30</span>] <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb88-7"><a href="analyse-simple-en-r-base.html#cb88-7" tabindex="-1"></a>df_1<span class="sc">$</span>imc_cl[df_1<span class="sc">$</span>imc <span class="sc">&gt;=</span> <span class="dv">30</span>] <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb88-8"><a href="analyse-simple-en-r-base.html#cb88-8" tabindex="-1"></a></span>
<span id="cb88-9"><a href="analyse-simple-en-r-base.html#cb88-9" tabindex="-1"></a><span class="do">### 2) avec la fonction ifelse de manière itérative : </span></span>
<span id="cb88-10"><a href="analyse-simple-en-r-base.html#cb88-10" tabindex="-1"></a>df_1<span class="sc">$</span>imc_cl <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df_1<span class="sc">$</span>imc <span class="sc">&lt;</span> <span class="fl">18.5</span>, <span class="dv">1</span>, </span>
<span id="cb88-11"><a href="analyse-simple-en-r-base.html#cb88-11" tabindex="-1"></a>                      <span class="fu">ifelse</span>(df_1<span class="sc">$</span>imc <span class="sc">&gt;=</span> <span class="fl">18.5</span> <span class="sc">&amp;</span> df_1<span class="sc">$</span>imc <span class="sc">&lt;</span> <span class="dv">25</span>, </span>
<span id="cb88-12"><a href="analyse-simple-en-r-base.html#cb88-12" tabindex="-1"></a>                             <span class="dv">2</span>, <span class="fu">ifelse</span>(df_1<span class="sc">$</span>imc <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> df_1<span class="sc">$</span>imc <span class="sc">&lt;</span> <span class="dv">30</span>, <span class="dv">3</span>, <span class="dv">4</span>)))</span>
<span id="cb88-13"><a href="analyse-simple-en-r-base.html#cb88-13" tabindex="-1"></a></span>
<span id="cb88-14"><a href="analyse-simple-en-r-base.html#cb88-14" tabindex="-1"></a><span class="do">### 3) avec une formule intégrant des conditions.</span></span>
<span id="cb88-15"><a href="analyse-simple-en-r-base.html#cb88-15" tabindex="-1"></a><span class="do">###    Comme on multiplie les résultats de conditions à des entiers, les </span></span>
<span id="cb88-16"><a href="analyse-simple-en-r-base.html#cb88-16" tabindex="-1"></a><span class="do">###    réponses TRUE et FALSE sont transformées en 1 et 0 par coercition</span></span>
<span id="cb88-17"><a href="analyse-simple-en-r-base.html#cb88-17" tabindex="-1"></a>df_1<span class="sc">$</span>imc_cl <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">*</span> (df_1<span class="sc">$</span>imc <span class="sc">&lt;</span> <span class="fl">18.5</span>) <span class="sc">+</span> </span>
<span id="cb88-18"><a href="analyse-simple-en-r-base.html#cb88-18" tabindex="-1"></a>                  <span class="dv">2</span> <span class="sc">*</span> (df_1<span class="sc">$</span>imc <span class="sc">&gt;=</span> <span class="fl">18.5</span> <span class="sc">&amp;</span> df_1<span class="sc">$</span>imc <span class="sc">&lt;</span> <span class="dv">25</span>) <span class="sc">+</span> </span>
<span id="cb88-19"><a href="analyse-simple-en-r-base.html#cb88-19" tabindex="-1"></a>                  <span class="dv">3</span> <span class="sc">*</span> (df_1<span class="sc">$</span>imc <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> df_1<span class="sc">$</span>imc <span class="sc">&lt;</span> <span class="dv">30</span>) <span class="sc">+</span> </span>
<span id="cb88-20"><a href="analyse-simple-en-r-base.html#cb88-20" tabindex="-1"></a>                  <span class="dv">4</span> <span class="sc">*</span> (df_1<span class="sc">$</span>imc <span class="sc">&gt;=</span> <span class="dv">30</span>))</span></code></pre></div>
<p>Pensez à vérifier que vous n’avez pas fait d’erreur en créant cette variable. Par exemple, on peut vérifier la distribution de l’IMC au sein des 4 classes à l’aide d’un box plot.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="analyse-simple-en-r-base.html#cb89-1" tabindex="-1"></a><span class="fu">boxplot</span>(df_1<span class="sc">$</span>imc <span class="sc">~</span> df_1<span class="sc">$</span>imc_cl) <span class="co"># imc en fonction de l&#39;imc en classe</span></span></code></pre></div>
<p><img src="_main_files/figure-html/create_verif2-1.png" width="672" /></p>
<p>Après avoir créé ces deux nouvelles variables, nous pouvons compléter la base de méta-données pour définir les noms de variables et de labels en clair. Pour cela, nous allons ajouter des lignes supplémentaires avec la fonction <code>rbind()</code> (<em>row bind</em> pour “fusion par rang”). <em>A noter qu’il existe aussi une fonction <code>cbind()</code> qui permet de fusionner des bases ou des matrices par colonnes</em></p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="analyse-simple-en-r-base.html#cb90-1" tabindex="-1"></a>meta_df_1 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(meta_df_1, </span>
<span id="cb90-2"><a href="analyse-simple-en-r-base.html#cb90-2" tabindex="-1"></a>                   <span class="fu">data.frame</span>(<span class="at">var =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;obesite&quot;</span>, <span class="dv">2</span>), </span>
<span id="cb90-3"><a href="analyse-simple-en-r-base.html#cb90-3" tabindex="-1"></a>                                      <span class="fu">rep</span>(<span class="st">&quot;imc_cl&quot;</span>, <span class="dv">4</span>)),</span>
<span id="cb90-4"><a href="analyse-simple-en-r-base.html#cb90-4" tabindex="-1"></a>                              <span class="at">label =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Obésité&quot;</span>, <span class="dv">2</span>), </span>
<span id="cb90-5"><a href="analyse-simple-en-r-base.html#cb90-5" tabindex="-1"></a>                                        <span class="fu">rep</span>(<span class="st">&quot;IMC en classes&quot;</span>, <span class="dv">4</span>)),</span>
<span id="cb90-6"><a href="analyse-simple-en-r-base.html#cb90-6" tabindex="-1"></a>                              <span class="at">id_labs =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>),</span>
<span id="cb90-7"><a href="analyse-simple-en-r-base.html#cb90-7" tabindex="-1"></a>                              <span class="at">code_labs =</span> <span class="fu">c</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>),</span>
<span id="cb90-8"><a href="analyse-simple-en-r-base.html#cb90-8" tabindex="-1"></a>                              <span class="at">labs =</span> <span class="fu">c</span>(<span class="st">&quot;Non&quot;</span>, <span class="st">&quot;Oui&quot;</span>,</span>
<span id="cb90-9"><a href="analyse-simple-en-r-base.html#cb90-9" tabindex="-1"></a>                                       <span class="st">&quot;Maigreur&quot;</span>, <span class="st">&quot;Normal&quot;</span>, <span class="st">&quot;Surpoids&quot;</span>, <span class="st">&quot;Obèse&quot;</span>))</span>
<span id="cb90-10"><a href="analyse-simple-en-r-base.html#cb90-10" tabindex="-1"></a>                   )</span>
<span id="cb90-11"><a href="analyse-simple-en-r-base.html#cb90-11" tabindex="-1"></a>meta_df_1</span></code></pre></div>
<pre><code>##        var               label id_labs code_labs         labs
## 1   subjid Identifiant patient       1        NA             
## 2      sex                Sexe       1         0      Féminin
## 3      sex                Sexe       2         1     Masculin
## 4      imc         IMC (kg/m²)       1        NA             
## 5    trait          Traitement       1         1      Placebo
## 6    trait          Traitement       2         2 Traitement A
## 7    trait          Traitement       3         3 Traitement B
## 8      pas          PAS (mmHg)       1        NA             
## 9  obesite             Obésité       1         0          Non
## 10 obesite             Obésité       2         1          Oui
## 11  imc_cl      IMC en classes       1         1     Maigreur
## 12  imc_cl      IMC en classes       2         2       Normal
## 13  imc_cl      IMC en classes       3         3     Surpoids
## 14  imc_cl      IMC en classes       4         4        Obèse</code></pre>
</div>
<div id="modifier-des-variables" class="section level3 hasAnchor" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Modifier des variables<a href="analyse-simple-en-r-base.html#modifier-des-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Enfin, nous souhaitons modifier la valeur de la pression artérielle du patient n°137 : suite à une erreur de saisie, nous nous sommes rendu compte que sa valeur n’est pas 133 mmHg, mais 123 mmHg.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="analyse-simple-en-r-base.html#cb92-1" tabindex="-1"></a>df_1<span class="sc">$</span>pas[df_1<span class="sc">$</span>subjid <span class="sc">==</span> <span class="dv">137</span>]</span></code></pre></div>
<pre><code>## [1] 133</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="analyse-simple-en-r-base.html#cb94-1" tabindex="-1"></a><span class="do">## nous pouvons directement assigner la nouvelle valeur avec l&#39;indexation par </span></span>
<span id="cb94-2"><a href="analyse-simple-en-r-base.html#cb94-2" tabindex="-1"></a><span class="do">## condition :</span></span>
<span id="cb94-3"><a href="analyse-simple-en-r-base.html#cb94-3" tabindex="-1"></a>df_1<span class="sc">$</span>pas[df_1<span class="sc">$</span>subjid <span class="sc">==</span> <span class="dv">137</span>] <span class="ot">&lt;-</span> <span class="dv">123</span></span>
<span id="cb94-4"><a href="analyse-simple-en-r-base.html#cb94-4" tabindex="-1"></a>df_1[df_1<span class="sc">$</span>subjid <span class="sc">%in%</span> <span class="dv">135</span><span class="sc">:</span><span class="dv">140</span>,] </span></code></pre></div>
<pre><code>##     subjid sex  imc trait pas obesite imc_cl
## 135    135   0 28.0     2 154       0      3
## 136    136   1 26.2     1 138       0      3
## 137    137   0 20.1     1 123       0      2
## 138    138   0 24.7     3 155       0      2
## 139    139   0 17.0     2 115       0      1
## 140    140   1 25.7     1 160       0      3</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="analyse-simple-en-r-base.html#cb96-1" tabindex="-1"></a><span class="co"># on voit que la valeur du patient 137 a bien été corrigée</span></span></code></pre></div>
</div>
</div>
<div id="analyses-univariées" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Analyses univariées<a href="#analyses-univari%C3%A9es" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="fonction-summary" class="section level3 hasAnchor" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> fonction <code>summary()</code><a href="analyse-simple-en-r-base.html#fonction-summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nous pouvons utiliser la fonction <code>summary()</code> pour obtenir de manière synthétique une description univariée de l’ensemble des variables, indiquant : les valeurs minimales et maximales, quartiles et médiane, et la valeur moyenne.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="analyse-simple-en-r-base.html#cb97-1" tabindex="-1"></a><span class="fu">summary</span>(df_1)</span></code></pre></div>
<pre><code>##      subjid            sex            imc            trait      
##  Min.   :  1.00   Min.   :0.00   Min.   :15.40   Min.   :1.000  
##  1st Qu.: 75.75   1st Qu.:0.00   1st Qu.:22.30   1st Qu.:1.000  
##  Median :150.50   Median :0.00   Median :24.60   Median :2.000  
##  Mean   :150.50   Mean   :0.49   Mean   :24.48   Mean   :1.897  
##  3rd Qu.:225.25   3rd Qu.:1.00   3rd Qu.:26.40   3rd Qu.:3.000  
##  Max.   :300.00   Max.   :1.00   Max.   :32.50   Max.   :3.000  
##       pas           obesite            imc_cl     
##  Min.   : 92.0   Min.   :0.00000   Min.   :1.000  
##  1st Qu.:125.0   1st Qu.:0.00000   1st Qu.:2.000  
##  Median :138.0   Median :0.00000   Median :2.000  
##  Mean   :137.1   Mean   :0.04333   Mean   :2.453  
##  3rd Qu.:149.0   3rd Qu.:0.00000   3rd Qu.:3.000  
##  Max.   :177.0   Max.   :1.00000   Max.   :4.000</code></pre>
<p>Les variables de la base <code>df_1</code> sont toutes codées en valeurs numériques, la fonction summary a donc décrit les variables qualitatives comme s’il s’agissait de variables quantitatives : ce n’est pas adapté.</p>
<p>Nous allons créer 2 nouvelles variables en <code>factor</code> à partir des variables qualitatives. Pour cela, nous allons également nous servir des informations indiquées dans la base de méta-données. Puis nous allons relancer la fonction <code>summary()</code> :</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="analyse-simple-en-r-base.html#cb99-1" tabindex="-1"></a><span class="do">### création de 2 variables de type &quot;factor&quot; à partir des variables sex et trait</span></span>
<span id="cb99-2"><a href="analyse-simple-en-r-base.html#cb99-2" tabindex="-1"></a>df_1<span class="sc">$</span>sexL <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_1<span class="sc">$</span>sex,</span>
<span id="cb99-3"><a href="analyse-simple-en-r-base.html#cb99-3" tabindex="-1"></a>                    <span class="at">labels =</span> meta_df_1<span class="sc">$</span>labs[meta_df_1<span class="sc">$</span>var <span class="sc">==</span> <span class="st">&quot;sex&quot;</span>])</span>
<span id="cb99-4"><a href="analyse-simple-en-r-base.html#cb99-4" tabindex="-1"></a>df_1<span class="sc">$</span>traitL <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_1<span class="sc">$</span>trait,</span>
<span id="cb99-5"><a href="analyse-simple-en-r-base.html#cb99-5" tabindex="-1"></a>                      <span class="at">labels =</span> meta_df_1<span class="sc">$</span>labs[meta_df_1<span class="sc">$</span>var <span class="sc">==</span> <span class="st">&quot;trait&quot;</span>])</span>
<span id="cb99-6"><a href="analyse-simple-en-r-base.html#cb99-6" tabindex="-1"></a><span class="fu">summary</span>(df_1)</span></code></pre></div>
<pre><code>##      subjid            sex            imc            trait      
##  Min.   :  1.00   Min.   :0.00   Min.   :15.40   Min.   :1.000  
##  1st Qu.: 75.75   1st Qu.:0.00   1st Qu.:22.30   1st Qu.:1.000  
##  Median :150.50   Median :0.00   Median :24.60   Median :2.000  
##  Mean   :150.50   Mean   :0.49   Mean   :24.48   Mean   :1.897  
##  3rd Qu.:225.25   3rd Qu.:1.00   3rd Qu.:26.40   3rd Qu.:3.000  
##  Max.   :300.00   Max.   :1.00   Max.   :32.50   Max.   :3.000  
##       pas           obesite            imc_cl            sexL    
##  Min.   : 92.0   Min.   :0.00000   Min.   :1.000   Féminin :153  
##  1st Qu.:125.0   1st Qu.:0.00000   1st Qu.:2.000   Masculin:147  
##  Median :138.0   Median :0.00000   Median :2.000                 
##  Mean   :137.1   Mean   :0.04333   Mean   :2.453                 
##  3rd Qu.:149.0   3rd Qu.:0.00000   3rd Qu.:3.000                 
##  Max.   :177.0   Max.   :1.00000   Max.   :4.000                 
##           traitL   
##  Placebo     :120  
##  Traitement A: 91  
##  Traitement B: 89  
##                    
##                    
## </code></pre>
<p>Les nouvelles variables <code>sexL</code> et <code>traitL</code> sont à présent décrites par dénombrement du nombre d’individus par modalité de réponse, de manière adaptée aux variables qualitatives.</p>
</div>
<div id="variables-quantitatives-1" class="section level3 hasAnchor" number="3.5.2">
<h3><span class="header-section-number">3.5.2</span> Variables quantitatives<a href="analyse-simple-en-r-base.html#variables-quantitatives-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pour décrire des variables quantitatives, on peut s’intéresser aux paramètres suivants :</p>
<ul>
<li>effectifs observés (non-manquants), avec les fonctions <code>length()</code> qui indique la longueur d’un vecteur, ou <code>nrow()</code> qui indique le nombre de lignes d’une base de données (ou d’une matrice)</li>
<li>moyenne, avec la fonction <code>mean()</code></li>
<li>écart type et variance, avec les fonctions <code>sd()</code> et <code>var()</code></li>
<li>minimum, 1er quartiles, médiane, 3ème quartile, maximum, avec les fonctions <code>min()</code>, <code>max()</code>, <code>median()</code>, <code>quantiles()</code></li>
</ul>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="analyse-simple-en-r-base.html#cb101-1" tabindex="-1"></a><span class="do">### Effectifs observés : </span></span>
<span id="cb101-2"><a href="analyse-simple-en-r-base.html#cb101-2" tabindex="-1"></a><span class="do">### Comme il n&#39;y a pas de manquant dans cette base, on peut directement utiliser</span></span>
<span id="cb101-3"><a href="analyse-simple-en-r-base.html#cb101-3" tabindex="-1"></a><span class="do">### la fonction length() ou nrow() pour connaître les effectifs </span></span>
<span id="cb101-4"><a href="analyse-simple-en-r-base.html#cb101-4" tabindex="-1"></a><span class="fu">nrow</span>(df_1) <span class="co"># 300</span></span>
<span id="cb101-5"><a href="analyse-simple-en-r-base.html#cb101-5" tabindex="-1"></a><span class="fu">length</span>(df_1<span class="sc">$</span>imc) <span class="co"># 300</span></span>
<span id="cb101-6"><a href="analyse-simple-en-r-base.html#cb101-6" tabindex="-1"></a></span>
<span id="cb101-7"><a href="analyse-simple-en-r-base.html#cb101-7" tabindex="-1"></a><span class="do">### Pour compter les effectifs non-manquants, de manière explicite :</span></span>
<span id="cb101-8"><a href="analyse-simple-en-r-base.html#cb101-8" tabindex="-1"></a><span class="fu">length</span>(df_1<span class="sc">$</span>imc[<span class="sc">!</span><span class="fu">is.na</span>(df_1<span class="sc">$</span>imc)]) <span class="co"># 300</span></span>
<span id="cb101-9"><a href="analyse-simple-en-r-base.html#cb101-9" tabindex="-1"></a></span>
<span id="cb101-10"><a href="analyse-simple-en-r-base.html#cb101-10" tabindex="-1"></a><span class="do">### moyennes</span></span>
<span id="cb101-11"><a href="analyse-simple-en-r-base.html#cb101-11" tabindex="-1"></a><span class="fu">mean</span>(df_1<span class="sc">$</span>imc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 24.481</span></span>
<span id="cb101-12"><a href="analyse-simple-en-r-base.html#cb101-12" tabindex="-1"></a><span class="fu">mean</span>(df_1<span class="sc">$</span>pas, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 137.1133</span></span>
<span id="cb101-13"><a href="analyse-simple-en-r-base.html#cb101-13" tabindex="-1"></a></span>
<span id="cb101-14"><a href="analyse-simple-en-r-base.html#cb101-14" tabindex="-1"></a><span class="do">### déviation standard (écart-type)</span></span>
<span id="cb101-15"><a href="analyse-simple-en-r-base.html#cb101-15" tabindex="-1"></a><span class="fu">sd</span>(df_1<span class="sc">$</span>imc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 3.069072</span></span>
<span id="cb101-16"><a href="analyse-simple-en-r-base.html#cb101-16" tabindex="-1"></a><span class="fu">sd</span>(df_1<span class="sc">$</span>pas, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 16.82053</span></span>
<span id="cb101-17"><a href="analyse-simple-en-r-base.html#cb101-17" tabindex="-1"></a></span>
<span id="cb101-18"><a href="analyse-simple-en-r-base.html#cb101-18" tabindex="-1"></a><span class="do">### variances</span></span>
<span id="cb101-19"><a href="analyse-simple-en-r-base.html#cb101-19" tabindex="-1"></a><span class="fu">var</span>(df_1<span class="sc">$</span>imc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 9.419203</span></span>
<span id="cb101-20"><a href="analyse-simple-en-r-base.html#cb101-20" tabindex="-1"></a><span class="fu">var</span>(df_1<span class="sc">$</span>pas, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 282.9303</span></span>
<span id="cb101-21"><a href="analyse-simple-en-r-base.html#cb101-21" tabindex="-1"></a></span>
<span id="cb101-22"><a href="analyse-simple-en-r-base.html#cb101-22" tabindex="-1"></a><span class="do">### quantiles</span></span>
<span id="cb101-23"><a href="analyse-simple-en-r-base.html#cb101-23" tabindex="-1"></a><span class="fu">min</span>(df_1<span class="sc">$</span>imc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 15.4</span></span>
<span id="cb101-24"><a href="analyse-simple-en-r-base.html#cb101-24" tabindex="-1"></a><span class="fu">min</span>(df_1<span class="sc">$</span>pas, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 92</span></span>
<span id="cb101-25"><a href="analyse-simple-en-r-base.html#cb101-25" tabindex="-1"></a></span>
<span id="cb101-26"><a href="analyse-simple-en-r-base.html#cb101-26" tabindex="-1"></a><span class="fu">max</span>(df_1<span class="sc">$</span>imc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 32.5</span></span>
<span id="cb101-27"><a href="analyse-simple-en-r-base.html#cb101-27" tabindex="-1"></a><span class="fu">max</span>(df_1<span class="sc">$</span>pas, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 177</span></span>
<span id="cb101-28"><a href="analyse-simple-en-r-base.html#cb101-28" tabindex="-1"></a></span>
<span id="cb101-29"><a href="analyse-simple-en-r-base.html#cb101-29" tabindex="-1"></a><span class="fu">median</span>(df_1<span class="sc">$</span>imc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 24.6</span></span>
<span id="cb101-30"><a href="analyse-simple-en-r-base.html#cb101-30" tabindex="-1"></a><span class="fu">median</span>(df_1<span class="sc">$</span>pas, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 138</span></span>
<span id="cb101-31"><a href="analyse-simple-en-r-base.html#cb101-31" tabindex="-1"></a></span>
<span id="cb101-32"><a href="analyse-simple-en-r-base.html#cb101-32" tabindex="-1"></a><span class="fu">quantile</span>(df_1<span class="sc">$</span>imc, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb101-33"><a href="analyse-simple-en-r-base.html#cb101-33" tabindex="-1"></a><span class="co">#   0%  25%  50%  75% 100% </span></span>
<span id="cb101-34"><a href="analyse-simple-en-r-base.html#cb101-34" tabindex="-1"></a><span class="co"># 15.4 22.3 24.6 26.4 32.5</span></span>
<span id="cb101-35"><a href="analyse-simple-en-r-base.html#cb101-35" tabindex="-1"></a><span class="fu">quantile</span>(df_1<span class="sc">$</span>pas, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb101-36"><a href="analyse-simple-en-r-base.html#cb101-36" tabindex="-1"></a>  <span class="co"># 0%  25%  50%  75% 100% </span></span>
<span id="cb101-37"><a href="analyse-simple-en-r-base.html#cb101-37" tabindex="-1"></a>  <span class="co"># 92  125  138  149  177</span></span></code></pre></div>
</div>
<div id="programmation-élémentaire" class="section level3 hasAnchor" number="3.5.3">
<h3><span class="header-section-number">3.5.3</span> Programmation élémentaire<a href="#programmation-%C3%A9l%C3%A9mentaire" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="créer-une-nouvelle-fonction" class="section level4 hasAnchor" number="3.5.3.1">
<h4><span class="header-section-number">3.5.3.1</span> Créer une nouvelle fonction<a href="#cr%C3%A9er-une-nouvelle-fonction" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Il est fastidieux de devoir récupérer les différents paramètres de distribution de chaque variable, un par un !</p>
<p>Mais R permet facilement de programmer de nouvelles fonctions “maison” à l’aide de <code>function(arguments) { expression }</code>, où on indique une liste d’<code>arguments</code> entre parenthèses, puis une liste de commandes à réaliser entre les accolades.</p>
<p>Par exemple, on peut créer une nouvelle fonction <code>exemple_fonction()</code> qui ajoute +2 à l’objet <code>x</code> :</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="analyse-simple-en-r-base.html#cb102-1" tabindex="-1"></a>seq_1a5 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span>
<span id="cb102-2"><a href="analyse-simple-en-r-base.html#cb102-2" tabindex="-1"></a>exemple_fonction <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {<span class="fu">return</span>(x <span class="sc">+</span> <span class="dv">2</span>)}</span>
<span id="cb102-3"><a href="analyse-simple-en-r-base.html#cb102-3" tabindex="-1"></a><span class="fu">exemple_fonction</span>(seq_1a5)</span></code></pre></div>
<pre><code>## [1] 3 4 5 6 7</code></pre>
<p>Pour accélérer notre analyse des variables quantitatives, nous allons créer <strong>une nouvelle fonction qui va calculer d’un coup l’ensemble des paramètres qui nous intéressent</strong>. Cette fonction sera nommée <code>univ_quanti</code>, elle va dépendre de 3 arguments :</p>
<ul>
<li><code>x</code>, la variable à décrire</li>
<li><code>dig</code>, le nombre de chiffres après la virgule pour présenter des valeurs arrondies</li>
<li><code>remove_miss</code>, une valeur logique qui sera utilisée pour exclure (ou non) les données manquantes du calcul (pour renseigner l’argument <code>na.rm</code> des fonctions descriptives de base)</li>
</ul>
<p>Entre accolades, on va demander à la fonction de :</p>
<ul>
<li>calculer les effectifs, la moyenne, l’écart type et les quantiles, de la variable <code>x</code></li>
<li>regrouper ces valeurs au sein d’un vecteur de réels, arrondis à <code>dig</code> chiffres après la virgule,</li>
<li>retourner le vecteur obtenu</li>
</ul>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="analyse-simple-en-r-base.html#cb104-1" tabindex="-1"></a><span class="do">### Définir une nouvelle fonction dans R</span></span>
<span id="cb104-2"><a href="analyse-simple-en-r-base.html#cb104-2" tabindex="-1"></a>univ_quanti <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="co"># la variable à décrire</span></span>
<span id="cb104-3"><a href="analyse-simple-en-r-base.html#cb104-3" tabindex="-1"></a>                        <span class="at">dig =</span> <span class="dv">2</span>, <span class="co"># par défaut, 2 chiffres après la virgule</span></span>
<span id="cb104-4"><a href="analyse-simple-en-r-base.html#cb104-4" tabindex="-1"></a>                        <span class="at">remove_miss =</span> <span class="cn">TRUE</span> <span class="co"># par défaut, la valeur est TRUE</span></span>
<span id="cb104-5"><a href="analyse-simple-en-r-base.html#cb104-5" tabindex="-1"></a>                        ) { <span class="co"># fermez la parenthèse et ouvrez l&#39;accolade</span></span>
<span id="cb104-6"><a href="analyse-simple-en-r-base.html#cb104-6" tabindex="-1"></a>  <span class="co"># on commence par calculer les différents paramètres et on les stocke dans </span></span>
<span id="cb104-7"><a href="analyse-simple-en-r-base.html#cb104-7" tabindex="-1"></a>  <span class="co"># les objets : &quot;n&quot;, &quot;moy&quot;, &quot;sd&quot; et &quot;q&quot;</span></span>
<span id="cb104-8"><a href="analyse-simple-en-r-base.html#cb104-8" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(x[<span class="sc">!</span><span class="fu">is.na</span>(x)])     </span>
<span id="cb104-9"><a href="analyse-simple-en-r-base.html#cb104-9" tabindex="-1"></a>  moy <span class="ot">&lt;-</span> <span class="fu">mean</span>(x, <span class="at">na.rm =</span> remove_miss)</span>
<span id="cb104-10"><a href="analyse-simple-en-r-base.html#cb104-10" tabindex="-1"></a>  sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(x, <span class="at">na.rm =</span> remove_miss)</span>
<span id="cb104-11"><a href="analyse-simple-en-r-base.html#cb104-11" tabindex="-1"></a>  q <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>), <span class="at">na.rm =</span> remove_miss)</span>
<span id="cb104-12"><a href="analyse-simple-en-r-base.html#cb104-12" tabindex="-1"></a>  </span>
<span id="cb104-13"><a href="analyse-simple-en-r-base.html#cb104-13" tabindex="-1"></a>  <span class="co"># on stocke les résultats dans un vecteur de réels, nommé &quot;param&quot;,</span></span>
<span id="cb104-14"><a href="analyse-simple-en-r-base.html#cb104-14" tabindex="-1"></a>  <span class="co"># en gardant uniquement la valeur arrondie pour la moyenne et l&#39;écart-type</span></span>
<span id="cb104-15"><a href="analyse-simple-en-r-base.html#cb104-15" tabindex="-1"></a>  param <span class="ot">&lt;-</span> <span class="fu">c</span>(n, </span>
<span id="cb104-16"><a href="analyse-simple-en-r-base.html#cb104-16" tabindex="-1"></a>             <span class="fu">round</span>(moy, <span class="at">digits =</span> dig), </span>
<span id="cb104-17"><a href="analyse-simple-en-r-base.html#cb104-17" tabindex="-1"></a>             <span class="fu">round</span>(sd, <span class="at">digits =</span> dig), </span>
<span id="cb104-18"><a href="analyse-simple-en-r-base.html#cb104-18" tabindex="-1"></a>             q)</span>
<span id="cb104-19"><a href="analyse-simple-en-r-base.html#cb104-19" tabindex="-1"></a>  <span class="co"># on peut ajouter un nom à chaque élément du vecteur &quot;param&quot;</span></span>
<span id="cb104-20"><a href="analyse-simple-en-r-base.html#cb104-20" tabindex="-1"></a>  <span class="fu">names</span>(param) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;N&quot;</span>, <span class="st">&quot;mean&quot;</span>, <span class="st">&quot;sd&quot;</span>, <span class="st">&quot;min&quot;</span>, <span class="st">&quot;Q1&quot;</span>, <span class="st">&quot;median&quot;</span>, <span class="st">&quot;Q3&quot;</span>, <span class="st">&quot;max&quot;</span>)</span>
<span id="cb104-21"><a href="analyse-simple-en-r-base.html#cb104-21" tabindex="-1"></a>  </span>
<span id="cb104-22"><a href="analyse-simple-en-r-base.html#cb104-22" tabindex="-1"></a>  <span class="co"># indiquer ce que doit retourner la fonction</span></span>
<span id="cb104-23"><a href="analyse-simple-en-r-base.html#cb104-23" tabindex="-1"></a>  <span class="fu">return</span>(param) </span>
<span id="cb104-24"><a href="analyse-simple-en-r-base.html#cb104-24" tabindex="-1"></a>} <span class="co"># fermez l&#39;accolade</span></span></code></pre></div>
<p>Si on applique cette fonction à nos deux variables quantitatives, on obtient l’ensemble des paramètres présentés dans un vecteur :</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="analyse-simple-en-r-base.html#cb105-1" tabindex="-1"></a><span class="fu">univ_quanti</span>(df_1<span class="sc">$</span>imc, <span class="at">dig =</span> <span class="dv">1</span>, <span class="at">remove_miss =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##      N   mean     sd    min     Q1 median     Q3    max 
##  300.0   24.5    3.1   15.4   22.3   24.6   26.4   32.5</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="analyse-simple-en-r-base.html#cb107-1" tabindex="-1"></a><span class="fu">univ_quanti</span>(df_1<span class="sc">$</span>pas, <span class="at">dig =</span> <span class="dv">1</span>, <span class="at">remove_miss =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##      N   mean     sd    min     Q1 median     Q3    max 
##  300.0  137.1   16.8   92.0  125.0  138.0  149.0  177.0</code></pre>
<p><em>Note : Vous pouvez remarquer qu’en utilisant cette fonction, les objets <code>n</code>, <code>moy</code>, <code>sd</code>, <code>q</code> et <code>param</code> n’apparaissent pas dans l’environnement de travail, ils ont uniquement été créés de manière temporaire au sein de la fonction.</em></p>
</div>
<div id="utiliser-des-boucles" class="section level4 hasAnchor" number="3.5.3.2">
<h4><span class="header-section-number">3.5.3.2</span> Utiliser des boucles<a href="analyse-simple-en-r-base.html#utiliser-des-boucles" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Les boucles <code>for</code> dans R permettent également d’automatiser des opérations en boucle. La syntaxe d’une boucle est :</p>
<ul>
<li><code>for (variable in sequence) { expession }</code> où l’<code>expression</code> entre accolade est répétée chaque fois que la <code>variable</code> est égale à une valeur de la <code>sequence</code></li>
</ul>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="analyse-simple-en-r-base.html#cb109-1" tabindex="-1"></a><span class="do">### exemple de boucle : </span></span>
<span id="cb109-2"><a href="analyse-simple-en-r-base.html#cb109-2" tabindex="-1"></a><span class="do">###  - pour chaque valeur i variant de 1 à 5,</span></span>
<span id="cb109-3"><a href="analyse-simple-en-r-base.html#cb109-3" tabindex="-1"></a><span class="do">###    =&gt; calcule 20 + i</span></span>
<span id="cb109-4"><a href="analyse-simple-en-r-base.html#cb109-4" tabindex="-1"></a><span class="do">###    =&gt; ajoute cette valeur à la fin de la phrase &quot;calcul de 20 + i = &quot;</span></span>
<span id="cb109-5"><a href="analyse-simple-en-r-base.html#cb109-5" tabindex="-1"></a><span class="do">###    =&gt; imprime le résultat à l&#39;écran</span></span>
<span id="cb109-6"><a href="analyse-simple-en-r-base.html#cb109-6" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) {</span>
<span id="cb109-7"><a href="analyse-simple-en-r-base.html#cb109-7" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">&quot;calcul de 20 + i = &quot;</span>, <span class="dv">20</span> <span class="sc">+</span> i))</span>
<span id="cb109-8"><a href="analyse-simple-en-r-base.html#cb109-8" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;calcul de 20 + i = 21&quot;
## [1] &quot;calcul de 20 + i = 22&quot;
## [1] &quot;calcul de 20 + i = 23&quot;
## [1] &quot;calcul de 20 + i = 24&quot;
## [1] &quot;calcul de 20 + i = 25&quot;</code></pre>
<p>On peut appliquer cette démarche pour répéter l’analyse univariée avec notre nouvelle fonction <code>univ_quanti()</code> à nos deux variables quantitatives. Les deux variables quantitatives sont dans les colonnes 3 et 5 de la base de données.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="analyse-simple-en-r-base.html#cb111-1" tabindex="-1"></a><span class="do">### Avec la fonction names(), on voit que les variables quantitatives imc et pas </span></span>
<span id="cb111-2"><a href="analyse-simple-en-r-base.html#cb111-2" tabindex="-1"></a><span class="do">### sont la 3ème et la 5ème variable de la base df_1</span></span>
<span id="cb111-3"><a href="analyse-simple-en-r-base.html#cb111-3" tabindex="-1"></a><span class="fu">names</span>(df_1)</span></code></pre></div>
<pre><code>## [1] &quot;subjid&quot;  &quot;sex&quot;     &quot;imc&quot;     &quot;trait&quot;   &quot;pas&quot;     &quot;obesite&quot; &quot;imc_cl&quot; 
## [8] &quot;sexL&quot;    &quot;traitL&quot;</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="analyse-simple-en-r-base.html#cb113-1" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>)) {</span>
<span id="cb113-2"><a href="analyse-simple-en-r-base.html#cb113-2" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">names</span>(df_1)[i]) <span class="co"># imprime le nom de la i-ème variable</span></span>
<span id="cb113-3"><a href="analyse-simple-en-r-base.html#cb113-3" tabindex="-1"></a>  <span class="co"># puis imprime les résultats de la fonction univ_quanti appliquée à la i-ème</span></span>
<span id="cb113-4"><a href="analyse-simple-en-r-base.html#cb113-4" tabindex="-1"></a>  <span class="co"># variable de la base df_1</span></span>
<span id="cb113-5"><a href="analyse-simple-en-r-base.html#cb113-5" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">univ_quanti</span>(df_1[[i]], <span class="at">dig =</span> <span class="dv">1</span>, <span class="at">remove_miss =</span> <span class="cn">TRUE</span>)) </span>
<span id="cb113-6"><a href="analyse-simple-en-r-base.html#cb113-6" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;imc&quot;
##      N   mean     sd    min     Q1 median     Q3    max 
##  300.0   24.5    3.1   15.4   22.3   24.6   26.4   32.5 
## [1] &quot;pas&quot;
##      N   mean     sd    min     Q1 median     Q3    max 
##  300.0  137.1   16.8   92.0  125.0  138.0  149.0  177.0</code></pre>
<p>Question bonus : que se passe t’il si vous n’indiquez pas la fonction <code>print()</code> ?</p>
<ul>
<li><em>réponse : il a fait tourner la fonction, mais ne l’a pas imprimé les résultats à l’écran</em></li>
</ul>
</div>
<div id="fonctions-apply-lapply-sapply" class="section level4 hasAnchor" number="3.5.3.3">
<h4><span class="header-section-number">3.5.3.3</span> Fonctions <code>apply()</code>, <code>lapply()</code>, <code>sapply()</code><a href="analyse-simple-en-r-base.html#fonctions-apply-lapply-sapply" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>On peut également lancer une fonction de manière répétée appliquée :</p>
<ul>
<li>à des colonnes ou des lignes de matrices (ou de data frame) avec la fonction <code>apply()</code></li>
<li>à des vecteurs ou des listes avec <code>lapply()</code> (qui retourne les résultats sous forme de liste) ou <code>sapply()</code> (qui retourne les résultats sous forme de matrice ou de vecteur)</li>
</ul>
<p><strong>Exemple 1 :</strong> La fonction <code>apply()</code> permet d’appliquer notre fonction de description des paramètres aux colonnes <code>"imc"</code> et <code>"pas"</code> de la la base <code>df_1</code> (Le résultat sera une matrice de réels) :</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="analyse-simple-en-r-base.html#cb115-1" tabindex="-1"></a><span class="fu">apply</span>(df_1[,<span class="fu">c</span>(<span class="st">&quot;imc&quot;</span>, <span class="st">&quot;pas&quot;</span>)], <span class="co"># matrice ou data.frame sélectionnée</span></span>
<span id="cb115-2"><a href="analyse-simple-en-r-base.html#cb115-2" tabindex="-1"></a>      <span class="at">MARGIN =</span> <span class="dv">2</span>, <span class="co"># 2 = par colonne ;  1 = par ligne</span></span>
<span id="cb115-3"><a href="analyse-simple-en-r-base.html#cb115-3" tabindex="-1"></a>      <span class="at">FUN =</span> univ_quanti, <span class="co"># fonction à utiliser</span></span>
<span id="cb115-4"><a href="analyse-simple-en-r-base.html#cb115-4" tabindex="-1"></a>      <span class="at">dig =</span> <span class="dv">1</span>, <span class="co"># on peut ajouter les arguments de la fonction à la suite</span></span>
<span id="cb115-5"><a href="analyse-simple-en-r-base.html#cb115-5" tabindex="-1"></a>      <span class="at">remove_miss =</span> <span class="cn">TRUE</span>) </span></code></pre></div>
<pre><code>##          imc   pas
## N      300.0 300.0
## mean    24.5 137.1
## sd       3.1  16.8
## min     15.4  92.0
## Q1      22.3 125.0
## median  24.6 138.0
## Q3      26.4 149.0
## max     32.5 177.0</code></pre>
<p><strong>Exemple 2 :</strong> La fonction <code>lapply()</code> applique la fonction à une liste de vecteurs et retourne une liste de la même longueur. La fonction <code>sapply()</code> fait la même chose, mais retourne les résultats sous forme de vecteur ou de matrice.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="analyse-simple-en-r-base.html#cb117-1" tabindex="-1"></a><span class="fu">lapply</span>(<span class="at">X =</span> df_1[,<span class="fu">c</span>(<span class="st">&quot;imc&quot;</span>, <span class="st">&quot;pas&quot;</span>)], </span>
<span id="cb117-2"><a href="analyse-simple-en-r-base.html#cb117-2" tabindex="-1"></a>      <span class="at">FUN =</span> univ_quanti,  <span class="co"># fonction à utiliser</span></span>
<span id="cb117-3"><a href="analyse-simple-en-r-base.html#cb117-3" tabindex="-1"></a>      <span class="at">dig =</span> <span class="dv">1</span>,</span>
<span id="cb117-4"><a href="analyse-simple-en-r-base.html#cb117-4" tabindex="-1"></a>      <span class="at">remove_miss =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## $imc
##      N   mean     sd    min     Q1 median     Q3    max 
##  300.0   24.5    3.1   15.4   22.3   24.6   26.4   32.5 
## 
## $pas
##      N   mean     sd    min     Q1 median     Q3    max 
##  300.0  137.1   16.8   92.0  125.0  138.0  149.0  177.0</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="analyse-simple-en-r-base.html#cb119-1" tabindex="-1"></a><span class="fu">sapply</span>(<span class="at">X =</span> df_1[,<span class="fu">c</span>(<span class="st">&quot;imc&quot;</span>, <span class="st">&quot;pas&quot;</span>)],  </span>
<span id="cb119-2"><a href="analyse-simple-en-r-base.html#cb119-2" tabindex="-1"></a>       <span class="at">FUN =</span> univ_quanti,  <span class="co"># fonction à utiliser</span></span>
<span id="cb119-3"><a href="analyse-simple-en-r-base.html#cb119-3" tabindex="-1"></a>       <span class="at">dig =</span> <span class="dv">1</span>,</span>
<span id="cb119-4"><a href="analyse-simple-en-r-base.html#cb119-4" tabindex="-1"></a>       <span class="at">remove_miss =</span> <span class="cn">TRUE</span>) </span></code></pre></div>
<pre><code>##          imc   pas
## N      300.0 300.0
## mean    24.5 137.1
## sd       3.1  16.8
## min     15.4  92.0
## Q1      22.3 125.0
## median  24.6 138.0
## Q3      26.4 149.0
## max     32.5 177.0</code></pre>
<p>Si on veut remplacer les noms de colonnes par les noms de variables en clair, on peut utiliser la base de méta-données :</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="analyse-simple-en-r-base.html#cb121-1" tabindex="-1"></a>res_quanti <span class="ot">&lt;-</span> <span class="fu">sapply</span>(df_1[,<span class="fu">c</span>(<span class="st">&quot;imc&quot;</span>, <span class="st">&quot;pas&quot;</span>)],</span>
<span id="cb121-2"><a href="analyse-simple-en-r-base.html#cb121-2" tabindex="-1"></a>                     <span class="at">FUN =</span> univ_quanti,</span>
<span id="cb121-3"><a href="analyse-simple-en-r-base.html#cb121-3" tabindex="-1"></a>                     <span class="at">dig =</span> <span class="dv">1</span>)</span>
<span id="cb121-4"><a href="analyse-simple-en-r-base.html#cb121-4" tabindex="-1"></a><span class="co"># on modifie le nom des colonne de la matrice de résultats</span></span>
<span id="cb121-5"><a href="analyse-simple-en-r-base.html#cb121-5" tabindex="-1"></a><span class="co"># avec les informations disponibles dans les méta-données</span></span>
<span id="cb121-6"><a href="analyse-simple-en-r-base.html#cb121-6" tabindex="-1"></a><span class="fu">colnames</span>(res_quanti) <span class="ot">&lt;-</span> <span class="fu">c</span>(meta_df_1<span class="sc">$</span>label[meta_df_1<span class="sc">$</span>var <span class="sc">==</span> <span class="st">&quot;imc&quot;</span>],</span>
<span id="cb121-7"><a href="analyse-simple-en-r-base.html#cb121-7" tabindex="-1"></a>                          meta_df_1<span class="sc">$</span>label[meta_df_1<span class="sc">$</span>var <span class="sc">==</span> <span class="st">&quot;pas&quot;</span>])</span>
<span id="cb121-8"><a href="analyse-simple-en-r-base.html#cb121-8" tabindex="-1"></a>res_quanti</span></code></pre></div>
<pre><code>##        IMC (kg/m²) PAS (mmHg)
## N            300.0      300.0
## mean          24.5      137.1
## sd             3.1       16.8
## min           15.4       92.0
## Q1            22.3      125.0
## median        24.6      138.0
## Q3            26.4      149.0
## max           32.5      177.0</code></pre>
</div>
</div>
<div id="variables-qualitatives-1" class="section level3 hasAnchor" number="3.5.4">
<h3><span class="header-section-number">3.5.4</span> Variables qualitatives<a href="analyse-simple-en-r-base.html#variables-qualitatives-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pour décrire les variables qualitatives,</p>
<ul>
<li>la fonction <code>table()</code> permet de décrire les effectifs dans chaque modalité de réponse,</li>
<li>la fonction <code>prop.table()</code> permet de décrire les pourcentages des données obtenues avec la fonction <code>table()</code>,</li>
</ul>
<p>On va utiliser les variables en “facteur” <code>sexL</code> et <code>traitL</code> dont les modalités de réponse sont labellisées.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="analyse-simple-en-r-base.html#cb123-1" tabindex="-1"></a><span class="do">### Description de la variable sex</span></span>
<span id="cb123-2"><a href="analyse-simple-en-r-base.html#cb123-2" tabindex="-1"></a><span class="fu">table</span>(df_1<span class="sc">$</span>sexL) <span class="co"># retourne un vecteur avec les effectifs</span></span></code></pre></div>
<pre><code>## 
##  Féminin Masculin 
##      153      147</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="analyse-simple-en-r-base.html#cb125-1" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(df_1<span class="sc">$</span>sexL)) <span class="co"># retourne un vecteur avec les pourcentages</span></span></code></pre></div>
<pre><code>## 
##  Féminin Masculin 
##     0.51     0.49</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="analyse-simple-en-r-base.html#cb127-1" tabindex="-1"></a><span class="do">### On peut combiner ces deux vecteurs avec cbind() (combinaison par colonne) </span></span>
<span id="cb127-2"><a href="analyse-simple-en-r-base.html#cb127-2" tabindex="-1"></a><span class="do">### pour les afficher dans une matrice </span></span>
<span id="cb127-3"><a href="analyse-simple-en-r-base.html#cb127-3" tabindex="-1"></a>tab_sex <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">table</span>(df_1<span class="sc">$</span>sexL), </span>
<span id="cb127-4"><a href="analyse-simple-en-r-base.html#cb127-4" tabindex="-1"></a>                 <span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(df_1<span class="sc">$</span>sexL)) <span class="sc">*</span> <span class="dv">100</span>, <span class="at">digits =</span> <span class="dv">1</span>))</span>
<span id="cb127-5"><a href="analyse-simple-en-r-base.html#cb127-5" tabindex="-1"></a><span class="fu">colnames</span>(tab_sex) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;n&quot;</span>, <span class="st">&quot;pct&quot;</span>)</span>
<span id="cb127-6"><a href="analyse-simple-en-r-base.html#cb127-6" tabindex="-1"></a>tab_sex</span></code></pre></div>
<pre><code>##            n pct
## Féminin  153  51
## Masculin 147  49</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="analyse-simple-en-r-base.html#cb129-1" tabindex="-1"></a><span class="do">### De même pour la variable traitement</span></span>
<span id="cb129-2"><a href="analyse-simple-en-r-base.html#cb129-2" tabindex="-1"></a>tab_trait <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">table</span>(df_1<span class="sc">$</span>traitL), </span>
<span id="cb129-3"><a href="analyse-simple-en-r-base.html#cb129-3" tabindex="-1"></a>                   <span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(df_1<span class="sc">$</span>traitL)) <span class="sc">*</span> <span class="dv">100</span>, <span class="at">digits =</span> <span class="dv">1</span>))</span>
<span id="cb129-4"><a href="analyse-simple-en-r-base.html#cb129-4" tabindex="-1"></a><span class="fu">colnames</span>(tab_trait) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;n&quot;</span>, <span class="st">&quot;pct&quot;</span>)</span>
<span id="cb129-5"><a href="analyse-simple-en-r-base.html#cb129-5" tabindex="-1"></a>tab_trait</span></code></pre></div>
<pre><code>##                n  pct
## Placebo      120 40.0
## Traitement A  91 30.3
## Traitement B  89 29.7</code></pre>
</div>
</div>
<div id="représentations-graphiques" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Représentations graphiques<a href="#repr%C3%A9sentations-graphiques" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Il est toujours utile de faire des représentations graphiques de la distribution des variables : cela permet d’avoir une bonne vision de l’ensemble des données et de détecter des anomalies éventuelles.</p>
<div id="distributions-univariées" class="section level3 hasAnchor" number="3.6.1">
<h3><span class="header-section-number">3.6.1</span> Distributions univariées<a href="#distributions-univari%C3%A9es" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La distribution des variables quantitatives peut être représentée à l’aide d’un histogramme <code>hist()</code>, d’une densité de kernel <code>density()</code> ou d’un box plot <code>boxplot()</code>.</p>
<p>Note : On peut modifier les paramètres des graphiques avec la fonction <code>par</code>. Par exemple <code>mfrow()</code> permet de combiner des figures par lignes et par colonnes.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="analyse-simple-en-r-base.html#cb131-1" tabindex="-1"></a><span class="do">### Variables quantitatives : imc et pas</span></span>
<span id="cb131-2"><a href="analyse-simple-en-r-base.html#cb131-2" tabindex="-1"></a><span class="do">### Histogrammes </span></span>
<span id="cb131-3"><a href="analyse-simple-en-r-base.html#cb131-3" tabindex="-1"></a><span class="fu">hist</span>(df_1<span class="sc">$</span>imc, <span class="at">xlab =</span> <span class="st">&quot;IMC (kg/m²)&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Histogramme de l&#39;IMC&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graph1-1.png" width="672" /></p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="analyse-simple-en-r-base.html#cb132-1" tabindex="-1"></a><span class="fu">hist</span>(df_1<span class="sc">$</span>pas, <span class="at">xlab =</span> <span class="st">&quot;PAS (mmHg)&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Histogramme de la PAS&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graph1-2.png" width="672" /></p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="analyse-simple-en-r-base.html#cb133-1" tabindex="-1"></a><span class="do">### On va afficher deux figures sur une 1 ligne et deux colonnes</span></span>
<span id="cb133-2"><a href="analyse-simple-en-r-base.html#cb133-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)) <span class="co"># indiquer c(X, Y) ou X = nb de lignes et Y = nb de colonnes</span></span>
<span id="cb133-3"><a href="analyse-simple-en-r-base.html#cb133-3" tabindex="-1"></a></span>
<span id="cb133-4"><a href="analyse-simple-en-r-base.html#cb133-4" tabindex="-1"></a><span class="do">### Densités de kernel</span></span>
<span id="cb133-5"><a href="analyse-simple-en-r-base.html#cb133-5" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(df_1<span class="sc">$</span>imc), <span class="at">xlab =</span> <span class="st">&quot;IMC (kg/m²)&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Fonction de densité - IMC&quot;</span>)</span>
<span id="cb133-6"><a href="analyse-simple-en-r-base.html#cb133-6" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(df_1<span class="sc">$</span>pas), <span class="at">xlab =</span> <span class="st">&quot;PAS (mmHg)&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Fonction de densité - PAS&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graph1-3.png" width="672" /></p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="analyse-simple-en-r-base.html#cb134-1" tabindex="-1"></a><span class="do">### Box plots</span></span>
<span id="cb134-2"><a href="analyse-simple-en-r-base.html#cb134-2" tabindex="-1"></a><span class="fu">boxplot</span>(df_1<span class="sc">$</span>imc, <span class="at">main =</span> <span class="st">&quot;Boxplot de l&#39;IMC&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;IMC (kg/m²)&quot;</span>)</span>
<span id="cb134-3"><a href="analyse-simple-en-r-base.html#cb134-3" tabindex="-1"></a><span class="fu">boxplot</span>(df_1<span class="sc">$</span>pas, <span class="at">main =</span> <span class="st">&quot;Boxplot de la PAS&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;PAS (mmHg)&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graph1-4.png" width="672" /></p>
<p>Les distributions des variables qualitatives peuvent être représentées par des diagrammes en barres <code>barplot()</code>.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="analyse-simple-en-r-base.html#cb135-1" tabindex="-1"></a><span class="do">### Diagrammes en barres, appliqués aux &quot;facteurs&quot;</span></span>
<span id="cb135-2"><a href="analyse-simple-en-r-base.html#cb135-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)) <span class="co"># 2 figures sur une seule ligne</span></span>
<span id="cb135-3"><a href="analyse-simple-en-r-base.html#cb135-3" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(df_1<span class="sc">$</span>sexL), <span class="co"># appliquer la fonction à une table()</span></span>
<span id="cb135-4"><a href="analyse-simple-en-r-base.html#cb135-4" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;N&quot;</span>,</span>
<span id="cb135-5"><a href="analyse-simple-en-r-base.html#cb135-5" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Diagramme en barres du traitement&quot;</span>) <span class="co"># avec les effectifs</span></span>
<span id="cb135-6"><a href="analyse-simple-en-r-base.html#cb135-6" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(df_1<span class="sc">$</span>sexL)),</span>
<span id="cb135-7"><a href="analyse-simple-en-r-base.html#cb135-7" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Frequency&quot;</span>,</span>
<span id="cb135-8"><a href="analyse-simple-en-r-base.html#cb135-8" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Diagramme en barres du traitement&quot;</span>) <span class="co"># avec les pourcentages</span></span></code></pre></div>
<p><img src="_main_files/figure-html/graph2-1.png" width="672" /></p>
</div>
<div id="distributions-bivariées" class="section level3 hasAnchor" number="3.6.2">
<h3><span class="header-section-number">3.6.2</span> Distributions bivariées<a href="#distributions-bivari%C3%A9es" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On peut croiser une variable quantitative en fonction des modalités d’une variable qualitative à l’aide de box-plots.</p>
<p>Une bonne pratique est d’indiquer clairement le noms des axes, les titres et légendes. Pour cela, nous pouvons utiliser la base de méta-données.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="analyse-simple-en-r-base.html#cb136-1" tabindex="-1"></a><span class="do">### Le signe &quot;tilde&quot; ~ est souvent utilisé pour définir une variable comme une </span></span>
<span id="cb136-2"><a href="analyse-simple-en-r-base.html#cb136-2" tabindex="-1"></a><span class="do">### fonction d&#39;une ou plusieurs autres variables : </span></span>
<span id="cb136-3"><a href="analyse-simple-en-r-base.html#cb136-3" tabindex="-1"></a><span class="do">### y = f(x1, x2, x3) s&#39;écrit y ~ x1 + x2 + x3</span></span>
<span id="cb136-4"><a href="analyse-simple-en-r-base.html#cb136-4" tabindex="-1"></a></span>
<span id="cb136-5"><a href="analyse-simple-en-r-base.html#cb136-5" tabindex="-1"></a><span class="do">### PAS en fonction du sex. </span></span>
<span id="cb136-6"><a href="analyse-simple-en-r-base.html#cb136-6" tabindex="-1"></a><span class="fu">boxplot</span>(df_1<span class="sc">$</span>pas <span class="sc">~</span> df_1<span class="sc">$</span>sexL, </span>
<span id="cb136-7"><a href="analyse-simple-en-r-base.html#cb136-7" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;PAS (mmHg)&quot;</span>,</span>
<span id="cb136-8"><a href="analyse-simple-en-r-base.html#cb136-8" tabindex="-1"></a>        <span class="at">xlab =</span> meta_df_1<span class="sc">$</span>label[meta_df_1<span class="sc">$</span>var <span class="sc">==</span> <span class="st">&quot;sex&quot;</span> <span class="sc">&amp;</span> meta_df_1<span class="sc">$</span>id_labs <span class="sc">==</span> <span class="dv">1</span>],</span>
<span id="cb136-9"><a href="analyse-simple-en-r-base.html#cb136-9" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Boxplot de la PAS&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graph3-1.png" width="672" /></p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="analyse-simple-en-r-base.html#cb137-1" tabindex="-1"></a><span class="do">### PAS en fonction du traitement</span></span>
<span id="cb137-2"><a href="analyse-simple-en-r-base.html#cb137-2" tabindex="-1"></a><span class="fu">boxplot</span>(df_1<span class="sc">$</span>pas <span class="sc">~</span> df_1<span class="sc">$</span>traitL, </span>
<span id="cb137-3"><a href="analyse-simple-en-r-base.html#cb137-3" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;PAS (mmHg)&quot;</span>,</span>
<span id="cb137-4"><a href="analyse-simple-en-r-base.html#cb137-4" tabindex="-1"></a>        <span class="at">xlab =</span> meta_df_1<span class="sc">$</span>label[meta_df_1<span class="sc">$</span>var <span class="sc">==</span> <span class="st">&quot;trait&quot;</span> <span class="sc">&amp;</span> meta_df_1<span class="sc">$</span>id_labs <span class="sc">==</span> <span class="dv">1</span>],</span>
<span id="cb137-5"><a href="analyse-simple-en-r-base.html#cb137-5" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Boxplot de la PAS&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graph3-2.png" width="672" /></p>
<p>Un nuage de points peut être utilisé pour représenter le croisement de deux variables quantitatives.</p>
<p>R offre beaucoup de possibilités pour modifier les paramètres graphiques. L’aide <code>?par</code> indique l’ensemble des options possibles. Il difficile d’y voir clair dans cette multitude d’options, les paramètres les plus utiles sont notamment :</p>
<ul>
<li><code>col</code> : pour spécifier la couleur des points et des lignes. Ce paramètre se décline à la couleur des axes <code>col.axis</code>, des labels <code>col.lab</code>, des titres <code>col.main</code>, des sous-titres <code>col.sub</code>, …</li>
<li><code>pch</code> : pour définir le symbole des points dans les nuages de points (0 pour un carré, 1 pour un rond, 2 pour un triange, etc). Cf. le détail de l’aide de <code>?points()</code></li>
<li><code>lty</code> : pour spécifier le type de ligne : 0 = <em>blank</em>, 1 = <em>solid</em>, 2 = <em>dashed</em>, etc. On peut également l’indiquer en caractère “blank”, “solid”, “dashed”, …. cf</li>
<li><code>lwd</code> : pour spécifier la largeur d’une ligne</li>
<li><code>cex</code> : valeur numérique indiquant la taille relative de la police de caractères. Elle se décline pour la police utilisée sur les axes <code>cex.axis</code>, les labels <code>cex.lab</code>, les titres <code>cex.main</code>, les sous-titres <code>cex.sub</code>, etc. Ce paramètre va également influencer la taille des points dans un nuage de points</li>
<li><code>mfrom</code> et <code>mfcol</code> pour combiner plusieurs graphiques sur une ou plusieurs lignes et une ou plusieurs colonnes</li>
<li><code>mar</code> : indique le nombre de ligne par marge, indiqué dans cet ordre <code>c(bottom, left, top, right)</code>. La valeur par défaut est <code>c(5, 4, 4, 2) + 0.1</code>. <code>mai</code> : permet également de préciser la taille des marges (en pouces), dans le même ordre <code>c(bottom, left, top, right)</code></li>
<li><code>legend</code> : permet d’ajouter une légende</li>
<li>etc.</li>
</ul>
<p>La fonction exemple permet d’avoir des exemples d’utilisation paramètres graphiques : <code>example(mar)</code>, <code>example(line)</code>, <code>example(axis)</code>, <code>example(legend)</code></p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="analyse-simple-en-r-base.html#cb138-1" tabindex="-1"></a><span class="do">### On peut représenter un nuage de points de la PAS en fonction de l&#39;IMC : </span></span>
<span id="cb138-2"><a href="analyse-simple-en-r-base.html#cb138-2" tabindex="-1"></a><span class="do">### où les hommes et les femmes ont deux symboles différents et les traitements </span></span>
<span id="cb138-3"><a href="analyse-simple-en-r-base.html#cb138-3" tabindex="-1"></a><span class="do">### deux couleurs différentes</span></span>
<span id="cb138-4"><a href="analyse-simple-en-r-base.html#cb138-4" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)) <span class="co"># pour revenir à un seul graphique par sortie</span></span>
<span id="cb138-5"><a href="analyse-simple-en-r-base.html#cb138-5" tabindex="-1"></a><span class="fu">plot.new</span>()</span>
<span id="cb138-6"><a href="analyse-simple-en-r-base.html#cb138-6" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">2</span>) <span class="sc">+</span> <span class="fl">0.1</span>) <span class="co"># paramètre des marges par défaut</span></span>
<span id="cb138-7"><a href="analyse-simple-en-r-base.html#cb138-7" tabindex="-1"></a><span class="fu">plot.window</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">35</span>), <span class="co"># range(df_1$imc)</span></span>
<span id="cb138-8"><a href="analyse-simple-en-r-base.html#cb138-8" tabindex="-1"></a>            <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">80</span>, <span class="dv">180</span>)) <span class="co"># range(df_1$pas)</span></span>
<span id="cb138-9"><a href="analyse-simple-en-r-base.html#cb138-9" tabindex="-1"></a><span class="fu">grid</span>() <span class="co"># ajoute une grille</span></span>
<span id="cb138-10"><a href="analyse-simple-en-r-base.html#cb138-10" tabindex="-1"></a><span class="do">### ajoute le nuage de points des femmes, groupe placebo</span></span>
<span id="cb138-11"><a href="analyse-simple-en-r-base.html#cb138-11" tabindex="-1"></a><span class="fu">points</span>(<span class="at">data =</span> <span class="fu">subset</span>(df_1, <span class="at">subset =</span> <span class="fu">c</span>(sex <span class="sc">==</span> <span class="st">&quot;Féminin&quot;</span> <span class="sc">&amp;</span> trait <span class="sc">==</span> <span class="st">&quot;Placebo&quot;</span>)), </span>
<span id="cb138-12"><a href="analyse-simple-en-r-base.html#cb138-12" tabindex="-1"></a>       pas <span class="sc">~</span> imc, </span>
<span id="cb138-13"><a href="analyse-simple-en-r-base.html#cb138-13" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;indianred3&quot;</span>, <span class="co"># placebo en rouge</span></span>
<span id="cb138-14"><a href="analyse-simple-en-r-base.html#cb138-14" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">4</span>) <span class="co"># femme avec une croix</span></span>
<span id="cb138-15"><a href="analyse-simple-en-r-base.html#cb138-15" tabindex="-1"></a><span class="co"># ajoute le nuage de points des femmes, groupe traitement A</span></span>
<span id="cb138-16"><a href="analyse-simple-en-r-base.html#cb138-16" tabindex="-1"></a><span class="fu">points</span>(<span class="at">data =</span> <span class="fu">subset</span>(df_1, <span class="at">subset =</span> <span class="fu">c</span>(sex <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> trait <span class="sc">==</span> <span class="dv">2</span>)), </span>
<span id="cb138-17"><a href="analyse-simple-en-r-base.html#cb138-17" tabindex="-1"></a>       pas <span class="sc">~</span> imc, </span>
<span id="cb138-18"><a href="analyse-simple-en-r-base.html#cb138-18" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="co"># traitement A en bleu</span></span>
<span id="cb138-19"><a href="analyse-simple-en-r-base.html#cb138-19" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">4</span>) <span class="co"># femme avec une croix</span></span>
<span id="cb138-20"><a href="analyse-simple-en-r-base.html#cb138-20" tabindex="-1"></a><span class="co"># ajoute le nuage de points des femmes, groupe traitement B</span></span>
<span id="cb138-21"><a href="analyse-simple-en-r-base.html#cb138-21" tabindex="-1"></a><span class="fu">points</span>(<span class="at">data =</span> <span class="fu">subset</span>(df_1, <span class="at">subset =</span> <span class="fu">c</span>(sex <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> trait <span class="sc">==</span> <span class="dv">3</span>)), </span>
<span id="cb138-22"><a href="analyse-simple-en-r-base.html#cb138-22" tabindex="-1"></a>       pas <span class="sc">~</span> imc, </span>
<span id="cb138-23"><a href="analyse-simple-en-r-base.html#cb138-23" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;palegreen3&quot;</span>, <span class="co"># traitement B en vert</span></span>
<span id="cb138-24"><a href="analyse-simple-en-r-base.html#cb138-24" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">4</span>) <span class="co"># femme avec une croix</span></span>
<span id="cb138-25"><a href="analyse-simple-en-r-base.html#cb138-25" tabindex="-1"></a><span class="co"># ajoute le nuage de points des hommes, groupe placebo</span></span>
<span id="cb138-26"><a href="analyse-simple-en-r-base.html#cb138-26" tabindex="-1"></a><span class="fu">points</span>(<span class="at">data =</span> <span class="fu">subset</span>(df_1, <span class="at">subset =</span> <span class="fu">c</span>(sex <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> trait <span class="sc">==</span> <span class="dv">1</span>)), </span>
<span id="cb138-27"><a href="analyse-simple-en-r-base.html#cb138-27" tabindex="-1"></a>       pas <span class="sc">~</span> imc, </span>
<span id="cb138-28"><a href="analyse-simple-en-r-base.html#cb138-28" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;indianred3&quot;</span>, <span class="co"># placebo en rouge</span></span>
<span id="cb138-29"><a href="analyse-simple-en-r-base.html#cb138-29" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>) <span class="co"># hommes avec un rond</span></span>
<span id="cb138-30"><a href="analyse-simple-en-r-base.html#cb138-30" tabindex="-1"></a><span class="co"># ajoute le nuage de points des hommes, groupe traitement A</span></span>
<span id="cb138-31"><a href="analyse-simple-en-r-base.html#cb138-31" tabindex="-1"></a><span class="fu">points</span>(<span class="at">data =</span> <span class="fu">subset</span>(df_1, <span class="at">subset =</span> <span class="fu">c</span>(sex <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> trait <span class="sc">==</span> <span class="dv">2</span>)), </span>
<span id="cb138-32"><a href="analyse-simple-en-r-base.html#cb138-32" tabindex="-1"></a>       pas <span class="sc">~</span> imc, </span>
<span id="cb138-33"><a href="analyse-simple-en-r-base.html#cb138-33" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;dodgerblue3&quot;</span>, <span class="co"># traitement A en bleu</span></span>
<span id="cb138-34"><a href="analyse-simple-en-r-base.html#cb138-34" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>) <span class="co"># hommes avec un rond</span></span>
<span id="cb138-35"><a href="analyse-simple-en-r-base.html#cb138-35" tabindex="-1"></a><span class="co"># ajoute le nuage de points des hommes, groupe traitement B</span></span>
<span id="cb138-36"><a href="analyse-simple-en-r-base.html#cb138-36" tabindex="-1"></a><span class="fu">points</span>(<span class="at">data =</span> <span class="fu">subset</span>(df_1, <span class="at">subset =</span> <span class="fu">c</span>(sex <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> trait <span class="sc">==</span> <span class="dv">3</span>)), </span>
<span id="cb138-37"><a href="analyse-simple-en-r-base.html#cb138-37" tabindex="-1"></a>       pas <span class="sc">~</span> imc, </span>
<span id="cb138-38"><a href="analyse-simple-en-r-base.html#cb138-38" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;palegreen3&quot;</span>, <span class="co"># traitement B en vert</span></span>
<span id="cb138-39"><a href="analyse-simple-en-r-base.html#cb138-39" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>) <span class="co"># hommes avec un rond</span></span>
<span id="cb138-40"><a href="analyse-simple-en-r-base.html#cb138-40" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="co"># axe du bas</span></span>
<span id="cb138-41"><a href="analyse-simple-en-r-base.html#cb138-41" tabindex="-1"></a>     <span class="at">lwd =</span> <span class="dv">1</span>, <span class="co"># largeur de la ligne</span></span>
<span id="cb138-42"><a href="analyse-simple-en-r-base.html#cb138-42" tabindex="-1"></a>     <span class="at">font.axis=</span><span class="dv">1</span>) <span class="co"># taille de la police de caractère</span></span>
<span id="cb138-43"><a href="analyse-simple-en-r-base.html#cb138-43" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="co"># axe à gauche</span></span>
<span id="cb138-44"><a href="analyse-simple-en-r-base.html#cb138-44" tabindex="-1"></a>     <span class="at">lwd =</span> <span class="dv">1</span>, <span class="co"># largeur de la ligne</span></span>
<span id="cb138-45"><a href="analyse-simple-en-r-base.html#cb138-45" tabindex="-1"></a>     <span class="at">font.axis=</span><span class="dv">1</span>) <span class="co"># taille de la police de caractère </span></span>
<span id="cb138-46"><a href="analyse-simple-en-r-base.html#cb138-46" tabindex="-1"></a><span class="fu">title</span>(<span class="at">xlab =</span> <span class="st">&quot;IMC (kg/m²)&quot;</span>)</span>
<span id="cb138-47"><a href="analyse-simple-en-r-base.html#cb138-47" tabindex="-1"></a><span class="fu">title</span>(<span class="at">ylab =</span> <span class="st">&quot;PAS (mmHg)&quot;</span>)</span>
<span id="cb138-48"><a href="analyse-simple-en-r-base.html#cb138-48" tabindex="-1"></a><span class="fu">title</span>(<span class="at">main =</span> <span class="st">&quot;Nuage de points de la PAS en fonction de l&#39;IMC&quot;</span>)</span>
<span id="cb138-49"><a href="analyse-simple-en-r-base.html#cb138-49" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>,</span>
<span id="cb138-50"><a href="analyse-simple-en-r-base.html#cb138-50" tabindex="-1"></a>       <span class="fu">c</span>(<span class="st">&quot;Femme, P&quot;</span>, <span class="st">&quot;Femme, A&quot;</span>, <span class="st">&quot;Femme, B&quot;</span>, </span>
<span id="cb138-51"><a href="analyse-simple-en-r-base.html#cb138-51" tabindex="-1"></a>         <span class="st">&quot;Homme, P&quot;</span>, <span class="st">&quot;Homme, A&quot;</span>, <span class="st">&quot;Homme, B&quot;</span>), </span>
<span id="cb138-52"><a href="analyse-simple-en-r-base.html#cb138-52" tabindex="-1"></a>       <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb138-53"><a href="analyse-simple-en-r-base.html#cb138-53" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;indianred3&quot;</span>, <span class="st">&quot;dodgerblue3&quot;</span>, <span class="st">&quot;palegreen3&quot;</span>,</span>
<span id="cb138-54"><a href="analyse-simple-en-r-base.html#cb138-54" tabindex="-1"></a>               <span class="st">&quot;indianred3&quot;</span>, <span class="st">&quot;dodgerblue3&quot;</span>, <span class="st">&quot;palegreen3&quot;</span>),</span>
<span id="cb138-55"><a href="analyse-simple-en-r-base.html#cb138-55" tabindex="-1"></a>       <span class="at">ncol =</span> <span class="dv">1</span>, </span>
<span id="cb138-56"><a href="analyse-simple-en-r-base.html#cb138-56" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.7</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/graph4-1.png" width="672" />
Pour trouver des informations détaillées sur l’utilisation des fonction graphiques de R base, vous pouvez lire le <a href="https://github.com/karoliskoncevicius/r_notes/blob/main/baseplotting.md">tutoriel détaillé de Karolis Koncevičius</a>.</p>
</div>
</div>
<div id="analyses-bivariées" class="section level2 hasAnchor" number="3.7">
<h2><span class="header-section-number">3.7</span> Analyses bivariées<a href="#analyses-bivari%C3%A9es" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Normalement, vous devriez savoir choisir quel test de comparaison utiliser en fonction des variables à comparer.
<img src="images/tests_bivaries.jpg" width="100%" style="display: block; margin: auto;" /></p>
<div id="variable-quantitative-times-qualitative" class="section level3 hasAnchor" number="3.7.1">
<h3><span class="header-section-number">3.7.1</span> Variable quantitative <span class="math inline">\(\times\)</span> qualitative<a href="analyse-simple-en-r-base.html#variable-quantitative-times-qualitative" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Pour décrire une variable quantitative en fonction d’une variable qualitative, on peut utiliser les fonctions <code>aggregate()</code> et <code>tapply()</code>.</p>
<p>La fonction <code>aggregate()</code> permet d’appliquer des fonctions (mean(), sd(), etc) à des sous-groupes de variables définies en facteurs.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="analyse-simple-en-r-base.html#cb139-1" tabindex="-1"></a><span class="do">### Description de la moyenne de l&#39;IMC et de la PAS en fonction du facteur sex</span></span>
<span id="cb139-2"><a href="analyse-simple-en-r-base.html#cb139-2" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="at">x =</span> df_1[,<span class="fu">c</span>(<span class="st">&quot;imc&quot;</span>, <span class="st">&quot;pas&quot;</span>)], <span class="co"># variable(s) quantitative(s)</span></span>
<span id="cb139-3"><a href="analyse-simple-en-r-base.html#cb139-3" tabindex="-1"></a>          <span class="at">by =</span> <span class="fu">list</span>(df_1<span class="sc">$</span>sexL), <span class="co"># en fonction du &quot;factor&quot; sexL</span></span>
<span id="cb139-4"><a href="analyse-simple-en-r-base.html#cb139-4" tabindex="-1"></a>          <span class="at">FUN =</span> mean) <span class="co"># fonction à appliquer à la variable x</span></span></code></pre></div>
<pre><code>##    Group.1      imc      pas
## 1  Féminin 24.09281 132.4248
## 2 Masculin 24.88503 141.9932</code></pre>
<p>Pour décrire de manière synthétique, la distribution, on veut récupérer l’effectif, la moyenne et l’écart-type par groupe. Nous allons modifier la fonction “maison” <code>univ_quanti()</code> que nous avions défini précédemment en ajoutant un argument <code>details</code> :</p>
<ul>
<li>si <code>details = TRUE</code>, alors la fonction retourne l’ensemble des résultats détaillés (effectifs, moyenne, écart-type, minimum, 1er quartile, médiane, 3ème quartile et maximum)</li>
<li>si <code>details = FALSE</code>, alors la fonction retourne uniquement les effectifs, la moyenne et l’écart-type.</li>
</ul>
<p>Pour cela nous allons compléter la fonction avec la construction <code>if(condition) {expression1} else {expression2}</code> : l’expression1 est appliquée si la condition est vraie, sinon l’expression2 est appliquée.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="analyse-simple-en-r-base.html#cb141-1" tabindex="-1"></a>univ_quanti <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">dig =</span> <span class="dv">2</span>, <span class="at">remove_miss =</span> <span class="cn">TRUE</span>, <span class="at">details =</span> <span class="cn">TRUE</span>) { </span>
<span id="cb141-2"><a href="analyse-simple-en-r-base.html#cb141-2" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(x[<span class="sc">!</span><span class="fu">is.na</span>(x)])     </span>
<span id="cb141-3"><a href="analyse-simple-en-r-base.html#cb141-3" tabindex="-1"></a>  moy <span class="ot">&lt;-</span> <span class="fu">mean</span>(x, <span class="at">na.rm =</span> remove_miss)</span>
<span id="cb141-4"><a href="analyse-simple-en-r-base.html#cb141-4" tabindex="-1"></a>  sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(x, <span class="at">na.rm =</span> remove_miss)</span>
<span id="cb141-5"><a href="analyse-simple-en-r-base.html#cb141-5" tabindex="-1"></a>  q <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>), <span class="at">na.rm =</span> remove_miss)</span>
<span id="cb141-6"><a href="analyse-simple-en-r-base.html#cb141-6" tabindex="-1"></a>  </span>
<span id="cb141-7"><a href="analyse-simple-en-r-base.html#cb141-7" tabindex="-1"></a>  <span class="co"># construction if (condition) {expression1} else {expression2}</span></span>
<span id="cb141-8"><a href="analyse-simple-en-r-base.html#cb141-8" tabindex="-1"></a>  <span class="cf">if</span> (details <span class="sc">==</span> <span class="cn">TRUE</span>) { <span class="co"># si la condition entre parenthèse est vraie ...</span></span>
<span id="cb141-9"><a href="analyse-simple-en-r-base.html#cb141-9" tabindex="-1"></a>    param <span class="ot">&lt;-</span> <span class="fu">c</span>(n,        <span class="co"># ... appliquer les fonctions entre accolades</span></span>
<span id="cb141-10"><a href="analyse-simple-en-r-base.html#cb141-10" tabindex="-1"></a>               <span class="fu">round</span>(moy, <span class="at">digits =</span> dig), </span>
<span id="cb141-11"><a href="analyse-simple-en-r-base.html#cb141-11" tabindex="-1"></a>               <span class="fu">round</span>(sd, <span class="at">digits =</span> dig), </span>
<span id="cb141-12"><a href="analyse-simple-en-r-base.html#cb141-12" tabindex="-1"></a>               q)</span>
<span id="cb141-13"><a href="analyse-simple-en-r-base.html#cb141-13" tabindex="-1"></a>  } <span class="cf">else</span> { <span class="co"># sinon appliquer les fonctions entre la 2ème accolade</span></span>
<span id="cb141-14"><a href="analyse-simple-en-r-base.html#cb141-14" tabindex="-1"></a>    param <span class="ot">&lt;-</span> <span class="fu">c</span>(n, </span>
<span id="cb141-15"><a href="analyse-simple-en-r-base.html#cb141-15" tabindex="-1"></a>               <span class="fu">round</span>(moy, <span class="at">digits =</span> dig), </span>
<span id="cb141-16"><a href="analyse-simple-en-r-base.html#cb141-16" tabindex="-1"></a>               <span class="fu">round</span>(sd, <span class="at">digits =</span> dig))</span>
<span id="cb141-17"><a href="analyse-simple-en-r-base.html#cb141-17" tabindex="-1"></a>  }</span>
<span id="cb141-18"><a href="analyse-simple-en-r-base.html#cb141-18" tabindex="-1"></a>  </span>
<span id="cb141-19"><a href="analyse-simple-en-r-base.html#cb141-19" tabindex="-1"></a>  <span class="co"># ajouter un nom à chaque élément du vecteur</span></span>
<span id="cb141-20"><a href="analyse-simple-en-r-base.html#cb141-20" tabindex="-1"></a>  <span class="cf">if</span> (details <span class="sc">==</span> <span class="cn">TRUE</span>) {</span>
<span id="cb141-21"><a href="analyse-simple-en-r-base.html#cb141-21" tabindex="-1"></a>    <span class="fu">names</span>(param) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;N&quot;</span>, <span class="st">&quot;mean&quot;</span>, <span class="st">&quot;sd&quot;</span>, <span class="st">&quot;min&quot;</span>, <span class="st">&quot;Q1&quot;</span>, <span class="st">&quot;median&quot;</span>, <span class="st">&quot;Q3&quot;</span>, <span class="st">&quot;max&quot;</span>)</span>
<span id="cb141-22"><a href="analyse-simple-en-r-base.html#cb141-22" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb141-23"><a href="analyse-simple-en-r-base.html#cb141-23" tabindex="-1"></a>    <span class="fu">names</span>(param) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;N&quot;</span>, <span class="st">&quot;mean&quot;</span>, <span class="st">&quot;sd&quot;</span>)</span>
<span id="cb141-24"><a href="analyse-simple-en-r-base.html#cb141-24" tabindex="-1"></a>  }</span>
<span id="cb141-25"><a href="analyse-simple-en-r-base.html#cb141-25" tabindex="-1"></a>  </span>
<span id="cb141-26"><a href="analyse-simple-en-r-base.html#cb141-26" tabindex="-1"></a>  <span class="co"># retourne les résultats</span></span>
<span id="cb141-27"><a href="analyse-simple-en-r-base.html#cb141-27" tabindex="-1"></a>  <span class="fu">return</span>(param)</span>
<span id="cb141-28"><a href="analyse-simple-en-r-base.html#cb141-28" tabindex="-1"></a>}</span>
<span id="cb141-29"><a href="analyse-simple-en-r-base.html#cb141-29" tabindex="-1"></a></span>
<span id="cb141-30"><a href="analyse-simple-en-r-base.html#cb141-30" tabindex="-1"></a><span class="do">### Description de la PAS en fonction du sexe (facteur sexL)</span></span>
<span id="cb141-31"><a href="analyse-simple-en-r-base.html#cb141-31" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="at">x =</span> df_1<span class="sc">$</span>pas, </span>
<span id="cb141-32"><a href="analyse-simple-en-r-base.html#cb141-32" tabindex="-1"></a>          <span class="at">by =</span> <span class="fu">list</span>(df_1<span class="sc">$</span>sexL), </span>
<span id="cb141-33"><a href="analyse-simple-en-r-base.html#cb141-33" tabindex="-1"></a>          <span class="at">FUN =</span> univ_quanti, <span class="co"># fonction à utiliser</span></span>
<span id="cb141-34"><a href="analyse-simple-en-r-base.html#cb141-34" tabindex="-1"></a>          <span class="at">dig =</span> <span class="dv">1</span>, <span class="at">remove_miss =</span> <span class="cn">TRUE</span>, <span class="at">details =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>##    Group.1   x.N x.mean  x.sd
## 1  Féminin 153.0  132.4  16.8
## 2 Masculin 147.0  142.0  15.5</code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="analyse-simple-en-r-base.html#cb143-1" tabindex="-1"></a><span class="do">### Description de la PAS en fonction du traitement (facteur traitL)</span></span>
<span id="cb143-2"><a href="analyse-simple-en-r-base.html#cb143-2" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="at">x =</span> df_1<span class="sc">$</span>pas, </span>
<span id="cb143-3"><a href="analyse-simple-en-r-base.html#cb143-3" tabindex="-1"></a>          <span class="at">by =</span> <span class="fu">list</span>(df_1<span class="sc">$</span>traitL), </span>
<span id="cb143-4"><a href="analyse-simple-en-r-base.html#cb143-4" tabindex="-1"></a>          <span class="at">FUN =</span> univ_quanti, <span class="co"># fonction à utiliser</span></span>
<span id="cb143-5"><a href="analyse-simple-en-r-base.html#cb143-5" tabindex="-1"></a>          <span class="at">dig =</span> <span class="dv">1</span>, <span class="at">remove_miss =</span> <span class="cn">TRUE</span>, <span class="at">details =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>##        Group.1   x.N x.mean  x.sd
## 1      Placebo 120.0  141.4  15.6
## 2 Traitement A  91.0  130.7  16.4
## 3 Traitement B  89.0  137.8  17.0</code></pre>
<p>La fonction <code>tapply()</code> permet également d’appliquer une fonction selon les sous-groupes d’un facteur (indiqué en argument <code>INDEX</code>). Les résultats obtenus sont au format de liste.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="analyse-simple-en-r-base.html#cb145-1" tabindex="-1"></a><span class="do">### Description de l&#39;IMC en fonction du sexe (facteur sexL)</span></span>
<span id="cb145-2"><a href="analyse-simple-en-r-base.html#cb145-2" tabindex="-1"></a><span class="fu">tapply</span>(<span class="at">X =</span> df_1<span class="sc">$</span>imc, </span>
<span id="cb145-3"><a href="analyse-simple-en-r-base.html#cb145-3" tabindex="-1"></a>       <span class="at">INDEX =</span> <span class="fu">list</span>(df_1<span class="sc">$</span>sexL), <span class="co"># facteur à indiquer sous forme de liste.</span></span>
<span id="cb145-4"><a href="analyse-simple-en-r-base.html#cb145-4" tabindex="-1"></a>       <span class="at">FUN =</span> univ_quanti, <span class="co"># fonction à utiliser sur la variable X</span></span>
<span id="cb145-5"><a href="analyse-simple-en-r-base.html#cb145-5" tabindex="-1"></a>       <span class="at">dig =</span> <span class="dv">1</span>, <span class="at">remove_miss =</span> <span class="cn">TRUE</span>, <span class="at">details =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## $Féminin
##     N  mean    sd 
## 153.0  24.1   3.1 
## 
## $Masculin
##     N  mean    sd 
## 147.0  24.9   3.0</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="analyse-simple-en-r-base.html#cb147-1" tabindex="-1"></a><span class="do">### Description de l&#39;IMC en fonction du sexe (facteur sexL)</span></span>
<span id="cb147-2"><a href="analyse-simple-en-r-base.html#cb147-2" tabindex="-1"></a><span class="fu">tapply</span>(<span class="at">X =</span> df_1<span class="sc">$</span>imc, </span>
<span id="cb147-3"><a href="analyse-simple-en-r-base.html#cb147-3" tabindex="-1"></a>       <span class="at">INDEX =</span> <span class="fu">list</span>(df_1<span class="sc">$</span>traitL), <span class="co"># facteur à indiquer sous forme de liste.</span></span>
<span id="cb147-4"><a href="analyse-simple-en-r-base.html#cb147-4" tabindex="-1"></a>       <span class="at">FUN =</span> univ_quanti, <span class="co"># fonction à utiliser sur la variable X</span></span>
<span id="cb147-5"><a href="analyse-simple-en-r-base.html#cb147-5" tabindex="-1"></a>       <span class="at">dig =</span> <span class="dv">1</span>, <span class="at">remove_miss =</span> <span class="cn">TRUE</span>, <span class="at">details =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## $Placebo
##     N  mean    sd 
## 120.0  24.3   2.9 
## 
## $`Traitement A`
##    N mean   sd 
## 91.0 24.8  3.0 
## 
## $`Traitement B`
##    N mean   sd 
## 89.0 24.3  3.3</code></pre>
</div>
<div id="variable-qualitative-times-qualitative" class="section level3 hasAnchor" number="3.7.2">
<h3><span class="header-section-number">3.7.2</span> Variable qualitative <span class="math inline">\(\times\)</span> qualitative<a href="analyse-simple-en-r-base.html#variable-qualitative-times-qualitative" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On peut décrire une variable qualitative en fonction d’une autre variable qualitative avec les fonctions <code>table()</code> et <code>prop.table(table())</code>.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="analyse-simple-en-r-base.html#cb149-1" tabindex="-1"></a><span class="do">### Décrire les effectifs de la variable sexL (en lignes),</span></span>
<span id="cb149-2"><a href="analyse-simple-en-r-base.html#cb149-2" tabindex="-1"></a><span class="do">### en fonction de la variable traitL (en colonnes) avec la fonction table()</span></span>
<span id="cb149-3"><a href="analyse-simple-en-r-base.html#cb149-3" tabindex="-1"></a><span class="do">### on va stocker les résultats dans un objet &quot;sex_by_trait_N&quot;</span></span>
<span id="cb149-4"><a href="analyse-simple-en-r-base.html#cb149-4" tabindex="-1"></a>sex_by_trait_N <span class="ot">&lt;-</span> <span class="fu">table</span>(df_1<span class="sc">$</span>sexL, df_1<span class="sc">$</span>traitL)</span>
<span id="cb149-5"><a href="analyse-simple-en-r-base.html#cb149-5" tabindex="-1"></a>sex_by_trait_N</span></code></pre></div>
<pre><code>##           
##            Placebo Traitement A Traitement B
##   Féminin       57           46           50
##   Masculin      63           45           39</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="analyse-simple-en-r-base.html#cb151-1" tabindex="-1"></a><span class="do">### Les pourcentages peuvent être décrits avec la fonction prop.table()</span></span>
<span id="cb151-2"><a href="analyse-simple-en-r-base.html#cb151-2" tabindex="-1"></a><span class="do">### il faut préciser l&#39;argument margin = 1 pour des pourcentages en ligne,</span></span>
<span id="cb151-3"><a href="analyse-simple-en-r-base.html#cb151-3" tabindex="-1"></a><span class="do">### ou margin = 2 pour des pourcentages en colonnes </span></span>
<span id="cb151-4"><a href="analyse-simple-en-r-base.html#cb151-4" tabindex="-1"></a><span class="do">### ou margin = NULL pour des pourcentages par cellule.</span></span>
<span id="cb151-5"><a href="analyse-simple-en-r-base.html#cb151-5" tabindex="-1"></a><span class="do">### on va stocker les pourcentage dans un objet &quot;sex_by_trait_pct&quot;</span></span>
<span id="cb151-6"><a href="analyse-simple-en-r-base.html#cb151-6" tabindex="-1"></a>sex_by_trait_pct <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(sex_by_trait_N,</span>
<span id="cb151-7"><a href="analyse-simple-en-r-base.html#cb151-7" tabindex="-1"></a>                               <span class="at">margin =</span> <span class="dv">2</span>) <span class="co">#  % par colonne </span></span>
<span id="cb151-8"><a href="analyse-simple-en-r-base.html#cb151-8" tabindex="-1"></a>sex_by_trait_pct</span></code></pre></div>
<pre><code>##           
##              Placebo Traitement A Traitement B
##   Féminin  0.4750000    0.5054945    0.5617978
##   Masculin 0.5250000    0.4945055    0.4382022</code></pre>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="analyse-simple-en-r-base.html#cb153-1" tabindex="-1"></a><span class="do">### On peut combiner ces deux résultats avec la fonction paste0() qui combine</span></span>
<span id="cb153-2"><a href="analyse-simple-en-r-base.html#cb153-2" tabindex="-1"></a><span class="do">### chaque élément de 2 vecteurs</span></span>
<span id="cb153-3"><a href="analyse-simple-en-r-base.html#cb153-3" tabindex="-1"></a>tab_biv_quali <span class="ot">&lt;-</span> <span class="fu">paste0</span>(sex_by_trait_N, </span>
<span id="cb153-4"><a href="analyse-simple-en-r-base.html#cb153-4" tabindex="-1"></a>                        <span class="st">&quot;(&quot;</span>, <span class="fu">round</span>(sex_by_trait_pct <span class="sc">*</span> <span class="dv">100</span>, <span class="at">digits =</span> <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)</span>
<span id="cb153-5"><a href="analyse-simple-en-r-base.html#cb153-5" tabindex="-1"></a>tab_biv_quali</span></code></pre></div>
<pre><code>## [1] &quot;57(47.5%)&quot; &quot;63(52.5%)&quot; &quot;46(50.5%)&quot; &quot;45(49.5%)&quot; &quot;50(56.2%)&quot; &quot;39(43.8%)&quot;</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="analyse-simple-en-r-base.html#cb155-1" tabindex="-1"></a><span class="do">### c&#39;est devenu un vecteur atomique de caractères</span></span>
<span id="cb155-2"><a href="analyse-simple-en-r-base.html#cb155-2" tabindex="-1"></a><span class="do">### on va lui redonner les dimensions et noms des matrices initiales</span></span>
<span id="cb155-3"><a href="analyse-simple-en-r-base.html#cb155-3" tabindex="-1"></a><span class="do">### en lui redonnant les attribut dim() et dimnames() des tables initiales</span></span>
<span id="cb155-4"><a href="analyse-simple-en-r-base.html#cb155-4" tabindex="-1"></a><span class="fu">dim</span>(tab_biv_quali) <span class="ot">&lt;-</span> <span class="fu">dim</span>(sex_by_trait_N)</span>
<span id="cb155-5"><a href="analyse-simple-en-r-base.html#cb155-5" tabindex="-1"></a><span class="fu">dimnames</span>(tab_biv_quali) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(sex_by_trait_N)</span>
<span id="cb155-6"><a href="analyse-simple-en-r-base.html#cb155-6" tabindex="-1"></a>tab_biv_quali</span></code></pre></div>
<pre><code>##           
##            Placebo     Traitement A Traitement B
##   Féminin  &quot;57(47.5%)&quot; &quot;46(50.5%)&quot;  &quot;50(56.2%)&quot; 
##   Masculin &quot;63(52.5%)&quot; &quot;45(49.5%)&quot;  &quot;39(43.8%)&quot;</code></pre>
</div>
<div id="comparer-2-moyennes" class="section level3 hasAnchor" number="3.7.3">
<h3><span class="header-section-number">3.7.3</span> Comparer 2 moyennes<a href="analyse-simple-en-r-base.html#comparer-2-moyennes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On peut <strong>comparer deux moyennes avec le test de Student</strong> <code>t.test()</code>.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="analyse-simple-en-r-base.html#cb157-1" tabindex="-1"></a><span class="do">### Comparaion de la moyenne de PAS en fonction du sexe (2 moyennes) </span></span>
<span id="cb157-2"><a href="analyse-simple-en-r-base.html#cb157-2" tabindex="-1"></a><span class="do">### par un test de Student</span></span>
<span id="cb157-3"><a href="analyse-simple-en-r-base.html#cb157-3" tabindex="-1"></a>ttest_pas_sex <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">data =</span> df_1, <span class="co"># préciser quelle est la base de donnée</span></span>
<span id="cb157-4"><a href="analyse-simple-en-r-base.html#cb157-4" tabindex="-1"></a>                        pas <span class="sc">~</span> sexL, <span class="co"># moyenne de la PAS en fonction du sexe</span></span>
<span id="cb157-5"><a href="analyse-simple-en-r-base.html#cb157-5" tabindex="-1"></a>                        <span class="at">var.equal =</span> <span class="cn">TRUE</span>) </span>
<span id="cb157-6"><a href="analyse-simple-en-r-base.html#cb157-6" tabindex="-1"></a><span class="do">## Attention, par défaut, l&#39;argument var.equal = FALSE</span></span>
<span id="cb157-7"><a href="analyse-simple-en-r-base.html#cb157-7" tabindex="-1"></a><span class="co"># il considère que l&#39;hypothèse d&#39;égalité des variances est fausse et applique</span></span>
<span id="cb157-8"><a href="analyse-simple-en-r-base.html#cb157-8" tabindex="-1"></a><span class="co"># un test de Welch qui est robuste, même en cas de variances inégales)</span></span>
<span id="cb157-9"><a href="analyse-simple-en-r-base.html#cb157-9" tabindex="-1"></a><span class="do">## Pour réaliser le test de Student, il faut indiquer : var.equal = TRUE</span></span>
<span id="cb157-10"><a href="analyse-simple-en-r-base.html#cb157-10" tabindex="-1"></a>ttest_pas_sex</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  pas by sexL
## t = -5.1297, df = 298, p-value = 5.239e-07
## alternative hypothesis: true difference in means between group Féminin and group Masculin is not equal to 0
## 95 percent confidence interval:
##  -13.239193  -5.897528
## sample estimates:
##  mean in group Féminin mean in group Masculin 
##               132.4248               141.9932</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="analyse-simple-en-r-base.html#cb159-1" tabindex="-1"></a><span class="do">## Les résultats indiquent que l&#39;on peut rejeter l&#39;hypothèse nulle d&#39;égalité des</span></span>
<span id="cb159-2"><a href="analyse-simple-en-r-base.html#cb159-2" tabindex="-1"></a><span class="do">## moyennes entre les hommes et les femmes, </span></span>
<span id="cb159-3"><a href="analyse-simple-en-r-base.html#cb159-3" tabindex="-1"></a><span class="do">## de manière statistiquement significative, avec une p-value = 5.2e-07</span></span>
<span id="cb159-4"><a href="analyse-simple-en-r-base.html#cb159-4" tabindex="-1"></a></span>
<span id="cb159-5"><a href="analyse-simple-en-r-base.html#cb159-5" tabindex="-1"></a><span class="do">## On peut récupérer des éléments spécifiques de la liste de résultats avec </span></span>
<span id="cb159-6"><a href="analyse-simple-en-r-base.html#cb159-6" tabindex="-1"></a><span class="do">## l&#39;opérateur dollar appliqué à l&#39;objet où on stocke les résultats :</span></span>
<span id="cb159-7"><a href="analyse-simple-en-r-base.html#cb159-7" tabindex="-1"></a>ttest_pas_sex<span class="sc">$</span>p.value <span class="co"># pour récupérer uniquement la p-value</span></span></code></pre></div>
<pre><code>## [1] 5.238798e-07</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="analyse-simple-en-r-base.html#cb161-1" tabindex="-1"></a>ttest_pas_sex<span class="sc">$</span>conf.int <span class="co"># pour l&#39;intervalle de confiance à 95% de la différence </span></span></code></pre></div>
<pre><code>## [1] -13.239193  -5.897528
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>Les <strong>conditions d’application du test de Student</strong> sont :</p>
<ul>
<li>l’égalité des variances</li>
<li>et la normalité de la distribution dans chaque groupe (surtout si les effectifs sont faibles). Dans notre exemple avec un effectif de 300, les résultats seront robuste même en cas d’écart à la normalité.</li>
</ul>
<p>Pour vérifier l’égalité des variance, on peut utiliser le test de Levene <code>leveneTest()</code> qui est disponible dans le package <code>car</code> qui n’est pas chargé en mémoire. Pour pouvoir utiliser le test de Levene, il faut :</p>
<ul>
<li>soit commencer par charger le package avec <code>library(car)</code>, puis lancer la fonction <code>leveneTest()</code></li>
<li>soit utiliser la syntaxe <code>car::leveneTest()</code> qui permet de lancer uniquement la fonction <code>leveneTest()</code> sans charger la totalité du package <code>car</code>.</li>
</ul>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="analyse-simple-en-r-base.html#cb163-1" tabindex="-1"></a><span class="co"># note : la variable en classe (sexe) doit être de type &quot;factor&quot;</span></span>
<span id="cb163-2"><a href="analyse-simple-en-r-base.html#cb163-2" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">leveneTest</span>(<span class="at">data =</span> df_1, pas <span class="sc">~</span> sexL) </span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1  1.0178 0.3139
##       298</code></pre>
<p>La p-value est égale à 0.31 : on ne rejette pas l’hypothèse nulle d’égalité des variances (par abus d’interprétation, on va considérer que la condition d’égalité des variances est vraie).</p>
<p>Pour vérifier la normalité de la distribution de la PAS par sexe, on peut tracer la densité de kernel dans chaque sous-groupe. Voici un exemple de programmation (qui ajoute une courbe normale en pointillés rouge pour servir de référence) :</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="analyse-simple-en-r-base.html#cb165-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)) <span class="co"># les 2 figures seront présentées sur 1 ligne</span></span>
<span id="cb165-2"><a href="analyse-simple-en-r-base.html#cb165-2" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>) {</span>
<span id="cb165-3"><a href="analyse-simple-en-r-base.html#cb165-3" tabindex="-1"></a>  vect <span class="ot">&lt;-</span> df_1<span class="sc">$</span>pas[<span class="fu">as.integer</span>(df_1<span class="sc">$</span>sexL) <span class="sc">==</span> i]</span>
<span id="cb165-4"><a href="analyse-simple-en-r-base.html#cb165-4" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="fu">density</span>(vect), <span class="co"># densité de kernel </span></span>
<span id="cb165-5"><a href="analyse-simple-en-r-base.html#cb165-5" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">attributes</span>(df_1<span class="sc">$</span>sexL)<span class="sc">$</span>levels[i])</span>
<span id="cb165-6"><a href="analyse-simple-en-r-base.html#cb165-6" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="fu">min</span>(vect), <span class="fu">max</span>(vect), <span class="fu">length</span>(<span class="dv">50</span>)), <span class="co"># loi normale de référence</span></span>
<span id="cb165-7"><a href="analyse-simple-en-r-base.html#cb165-7" tabindex="-1"></a>        <span class="at">y =</span> <span class="fu">dnorm</span>(<span class="fu">seq</span>(<span class="fu">min</span>(vect), <span class="fu">max</span>(vect), <span class="fu">length</span>(<span class="dv">50</span>)),</span>
<span id="cb165-8"><a href="analyse-simple-en-r-base.html#cb165-8" tabindex="-1"></a>                  <span class="at">mean =</span> <span class="fu">mean</span>(vect),</span>
<span id="cb165-9"><a href="analyse-simple-en-r-base.html#cb165-9" tabindex="-1"></a>                  <span class="at">sd =</span> <span class="fu">sd</span>(vect)),</span>
<span id="cb165-10"><a href="analyse-simple-en-r-base.html#cb165-10" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb165-11"><a href="analyse-simple-en-r-base.html#cb165-11" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="_main_files/figure-html/bivarie7-1.png" width="672" /></p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="analyse-simple-en-r-base.html#cb166-1" tabindex="-1"></a><span class="fu">rm</span>(vect) <span class="co"># supprime l&#39;objet &quot;vect&quot; qui n&#39;est plus utile</span></span></code></pre></div>
<p>Ici, les distributions semblent assez proches de lois normales.</p>
<p><strong>Si les conditions d’application du test de Student ne sont pas vérifiées</strong>, on peut utiliser le test des rangs de Wilcoxon-Mann-Whitney <code>wilcox.test()</code> ).</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="analyse-simple-en-r-base.html#cb167-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(<span class="at">data =</span> df_1, pas <span class="sc">~</span> sex) <span class="co"># p-value = 1.529e-06</span></span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  pas by sex
## W = 7609.5, p-value = 1.29e-06
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Le test de Wilcoxon rejette l’hypothèse nulle d’égalité des moyennes de PAS entre les hommes et les femmes (de manière significative, avec une p-value = 1.5e-06).</p>
</div>
<div id="comparer-3-moyennes-ou-plus" class="section level3 hasAnchor" number="3.7.4">
<h3><span class="header-section-number">3.7.4</span> Comparer 3 moyennes ou plus<a href="analyse-simple-en-r-base.html#comparer-3-moyennes-ou-plus" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On peut <strong>comparer 3 moyennes ou plus avec une Anova</strong> <code>anova()</code>. Par exemple, si on compare la moyenne de PAS en fonction du traitement, l’hypothèse nulle est : <em>“il n’existe pas de différence de moyenne de PAS entre les 3 groupes de traitement”</em>.</p>
<p>Dans R, la fonction <code>anova()</code> s’applique au résultat d’un modèle linéaire. Nous allons donc d’abord estimer le modèle linéaire de la pression artérielle systolique en fonction du traitement avec la fonction <code>lm()</code> (pour <em>linear model</em>). Nous pourrons également utiliser les résidus de ce modèle pour vérifier la condition de normalité. La condition d’égalité des variances pourra être vérifiée comme précédemment avec le test de Levenne.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="analyse-simple-en-r-base.html#cb169-1" tabindex="-1"></a>mod_pas_trait <span class="ot">&lt;-</span> <span class="fu">lm</span>(pas <span class="sc">~</span> traitL, <span class="co"># modèle de PAS en fonction du traitement</span></span>
<span id="cb169-2"><a href="analyse-simple-en-r-base.html#cb169-2" tabindex="-1"></a>                    <span class="at">data =</span> df_1)</span>
<span id="cb169-3"><a href="analyse-simple-en-r-base.html#cb169-3" tabindex="-1"></a><span class="co"># le fait d&#39;utiliser un &quot;factor&quot; (traitL) comme variable explicative</span></span>
<span id="cb169-4"><a href="analyse-simple-en-r-base.html#cb169-4" tabindex="-1"></a><span class="co"># va permettre à R de créer automatiquement deux indicatrices pour modéliser</span></span>
<span id="cb169-5"><a href="analyse-simple-en-r-base.html#cb169-5" tabindex="-1"></a><span class="co"># le traitement à 3 catégories, en prenant la première catégorie (&quot;placebo&quot;)</span></span>
<span id="cb169-6"><a href="analyse-simple-en-r-base.html#cb169-6" tabindex="-1"></a><span class="co"># comme référence</span></span>
<span id="cb169-7"><a href="analyse-simple-en-r-base.html#cb169-7" tabindex="-1"></a><span class="fu">summary</span>(mod_pas_trait)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = pas ~ traitL, data = df_1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.747 -11.747   0.157  11.340  39.157 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         141.400      1.486  95.182  &lt; 2e-16 ***
## traitLTraitement A  -10.653      2.262  -4.709 3.82e-06 ***
## traitLTraitement B   -3.557      2.277  -1.563    0.119    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.27 on 297 degrees of freedom
## Multiple R-squared:  0.07022,    Adjusted R-squared:  0.06396 
## F-statistic: 11.22 on 2 and 297 DF,  p-value: 2.016e-05</code></pre>
<p>Le modèle linéaire indique que :</p>
<ul>
<li>la PAS est en moyenne de 141.4 mmHg dans le groupe de référence (placebo) avec l’intercept.</li>
<li>la PAS est plus faible de -10.7 mmHg en moyenne dans le groupe “traitement A” par rapport au placebo (de manière significative, p = 3.8e-06)</li>
<li>la PAS est plus faible de -3.6 mmHg en moyenne dans le groupe “traitement B” par rapport au placebo (de manière non significative, p = 0.12)</li>
</ul>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="analyse-simple-en-r-base.html#cb171-1" tabindex="-1"></a><span class="do">## On applique ensuite ce modèle linéaire à la fonction anova</span></span>
<span id="cb171-2"><a href="analyse-simple-en-r-base.html#cb171-2" tabindex="-1"></a><span class="do">## qui va retourner une table d&#39;Anova avec les différentes sources de </span></span>
<span id="cb171-3"><a href="analyse-simple-en-r-base.html#cb171-3" tabindex="-1"></a><span class="do">## variabilité, degrés de liberté, sommes des carrés, carrés moyens, </span></span>
<span id="cb171-4"><a href="analyse-simple-en-r-base.html#cb171-4" tabindex="-1"></a><span class="do">## statistique F du test de Fisher et p-value.</span></span>
<span id="cb171-5"><a href="analyse-simple-en-r-base.html#cb171-5" tabindex="-1"></a>anova_pas_trait <span class="ot">&lt;-</span> <span class="fu">anova</span>(mod_pas_trait) </span>
<span id="cb171-6"><a href="analyse-simple-en-r-base.html#cb171-6" tabindex="-1"></a>anova_pas_trait</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: pas
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## traitL      2   5940 2970.18  11.215 2.016e-05 ***
## Residuals 297  78656  264.83                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="analyse-simple-en-r-base.html#cb173-1" tabindex="-1"></a><span class="do">## on peut récupérer des résultats spécifiques avec l&#39;opérateur dollar</span></span>
<span id="cb173-2"><a href="analyse-simple-en-r-base.html#cb173-2" tabindex="-1"></a>anova_pas_trait<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span> <span class="co"># récupère uniquement la p-value</span></span></code></pre></div>
<pre><code>## [1] 2.015778e-05           NA</code></pre>
<p>On peut vérifier la condition d’égalité des variances avec un test de Levenne :</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="analyse-simple-en-r-base.html#cb175-1" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">leveneTest</span>(<span class="at">data =</span> df_1, pas <span class="sc">~</span> traitL) <span class="co"># p = 0.4703   OK</span></span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   2  0.6669  0.514
##       297</code></pre>
<p>On ne rejette pas l’hypothèse nulle d’égalité des variances, car la p-value n’est pas significative (p = 0.51). Par abus d’interprétation, on considère que les variances sont égales.</p>
<p>Pour vérifier la condition de normalité, on va évaluer la normalité des résidus du modèle linéaire.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="analyse-simple-en-r-base.html#cb177-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)) <span class="co"># 2 graphiques sur 1 ligne</span></span>
<span id="cb177-2"><a href="analyse-simple-en-r-base.html#cb177-2" tabindex="-1"></a></span>
<span id="cb177-3"><a href="analyse-simple-en-r-base.html#cb177-3" tabindex="-1"></a><span class="do">### On peut récupérer les résidus du modèle linéaire avec l&#39;opérateur dollar</span></span>
<span id="cb177-4"><a href="analyse-simple-en-r-base.html#cb177-4" tabindex="-1"></a><span class="do">### Représenter les résidus dans un QQ-plot</span></span>
<span id="cb177-5"><a href="analyse-simple-en-r-base.html#cb177-5" tabindex="-1"></a><span class="fu">qqnorm</span>(mod_pas_trait<span class="sc">$</span>residuals) </span>
<span id="cb177-6"><a href="analyse-simple-en-r-base.html#cb177-6" tabindex="-1"></a><span class="fu">qqline</span>(mod_pas_trait<span class="sc">$</span>residuals)</span>
<span id="cb177-7"><a href="analyse-simple-en-r-base.html#cb177-7" tabindex="-1"></a></span>
<span id="cb177-8"><a href="analyse-simple-en-r-base.html#cb177-8" tabindex="-1"></a><span class="do">### Représenter la distribution des résidus par une densité de kernel</span></span>
<span id="cb177-9"><a href="analyse-simple-en-r-base.html#cb177-9" tabindex="-1"></a>vect <span class="ot">&lt;-</span> mod_pas_trait<span class="sc">$</span>residuals</span>
<span id="cb177-10"><a href="analyse-simple-en-r-base.html#cb177-10" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(vect), <span class="co"># densité de kernel </span></span>
<span id="cb177-11"><a href="analyse-simple-en-r-base.html#cb177-11" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb177-12"><a href="analyse-simple-en-r-base.html#cb177-12" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="fu">min</span>(vect), <span class="fu">max</span>(vect), <span class="fu">length</span>(<span class="dv">50</span>)), <span class="co"># loi normale de référence</span></span>
<span id="cb177-13"><a href="analyse-simple-en-r-base.html#cb177-13" tabindex="-1"></a>      <span class="at">y =</span> <span class="fu">dnorm</span>(<span class="fu">seq</span>(<span class="fu">min</span>(vect), <span class="fu">max</span>(vect), <span class="fu">length</span>(<span class="dv">50</span>)),</span>
<span id="cb177-14"><a href="analyse-simple-en-r-base.html#cb177-14" tabindex="-1"></a>                <span class="at">mean =</span> <span class="fu">mean</span>(vect),</span>
<span id="cb177-15"><a href="analyse-simple-en-r-base.html#cb177-15" tabindex="-1"></a>                <span class="at">sd =</span> <span class="fu">sd</span>(vect)),</span>
<span id="cb177-16"><a href="analyse-simple-en-r-base.html#cb177-16" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/bivarie12-1.png" width="672" /></p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="analyse-simple-en-r-base.html#cb178-1" tabindex="-1"></a><span class="fu">rm</span>(vect)</span></code></pre></div>
<p>La condition normalité semble acceptable.</p>
<p>Si les variances avaient été inégales, on aurait appliqué un test de Kruskal-Wallis, avec la fonction <code>kruskal.test()</code>.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="analyse-simple-en-r-base.html#cb179-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(pas <span class="sc">~</span> traitL, <span class="at">data =</span> df_1) <span class="co"># p-value = 7.336e-05</span></span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  pas by traitL
## Kruskal-Wallis chi-squared = 19.04, df = 2, p-value = 7.336e-05</code></pre>
<p>Le test de Kruskal-Wallis rejette l’hypothèse nulle d’égalité des moyenne entre les 3 groupes de traitement, de manière significative (p = 7.3e-05).</p>
</div>
<div id="comparer-des-pourcentages" class="section level3 hasAnchor" number="3.7.5">
<h3><span class="header-section-number">3.7.5</span> Comparer des pourcentages<a href="analyse-simple-en-r-base.html#comparer-des-pourcentages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On peut <strong>comparer plusieurs pourcentages avec un test du chi-2</strong> <code>chisq.test()</code>.</p>
<p>Par exemple, nous allons tester l’hypothèse nulle suivante :
_“H0 : La répartition par sexe est la même dans les 3 groupes de traitement_”</p>
<p>Pour répondre à la question, nous pouvons faire un test comparant le pourcentage d’hommes et de femmes au sein des 3 groupes de traitement. Nous avons déjà vu que les fonction <code>table()</code> et <code>prop.table(table())</code> permettaient de décrire la répartition du traitement en fonction du sexe.</p>
<p>La fonction <code>chisq.test()</code> va s’appliquer à un tableau croisé des effectifs par traiement et par sexe. On rappelle que les conditions d’application à vérifier sont que tous les effectifs attendus doivent être <span class="math inline">\(\geq 5\)</span>.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="analyse-simple-en-r-base.html#cb181-1" tabindex="-1"></a><span class="do">### Appliquer un test du chi2 au tableau croisé du traitement en fonction du sex</span></span>
<span id="cb181-2"><a href="analyse-simple-en-r-base.html#cb181-2" tabindex="-1"></a><span class="co"># Attention, par défaut la fonction chisq.test applique la correction de Yates </span></span>
<span id="cb181-3"><a href="analyse-simple-en-r-base.html#cb181-3" tabindex="-1"></a><span class="co"># en indiquant correct = FALSE</span></span>
<span id="cb181-4"><a href="analyse-simple-en-r-base.html#cb181-4" tabindex="-1"></a><span class="co"># cette correction n&#39;est utile que si les conditions d&#39;application du test</span></span>
<span id="cb181-5"><a href="analyse-simple-en-r-base.html#cb181-5" tabindex="-1"></a><span class="co"># du chi-2 ne sont pas vérifiées.</span></span>
<span id="cb181-6"><a href="analyse-simple-en-r-base.html#cb181-6" tabindex="-1"></a>chi2 <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="fu">table</span>(df_1<span class="sc">$</span>sexL, df_1<span class="sc">$</span>traitL), </span>
<span id="cb181-7"><a href="analyse-simple-en-r-base.html#cb181-7" tabindex="-1"></a>                   <span class="at">correct =</span> <span class="cn">FALSE</span>) </span>
<span id="cb181-8"><a href="analyse-simple-en-r-base.html#cb181-8" tabindex="-1"></a>chi2</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  table(df_1$sexL, df_1$traitL)
## X-squared = 1.5512, df = 2, p-value = 0.4604</code></pre>
<p>D’après ces résultats, on ne rejette pas l’hypothèse nulle d’égalité de la répartition par sexe dans les 3 groupes de traitement (p = 0.46)</p>
<p>Pour récupérer la table des effectifs attendus et vérifier les conditions d’application, on peut utiliser l’opérateur dollar <code>$expected</code> :</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="analyse-simple-en-r-base.html#cb183-1" tabindex="-1"></a>chi2<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>##           
##            Placebo Traitement A Traitement B
##   Féminin     61.2        46.41        45.39
##   Masculin    58.8        44.59        43.61</code></pre>
<p>On voit que la condition d’application est vérifiée car tous les effectifs attendus sont <span class="math inline">\(\geq 5\)</span>.</p>
<p>Si les conditions n’avaient pas été vérifiées, on aurait pu appliquer un test exact de Fisher <code>fisher.test()</code></p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="analyse-simple-en-r-base.html#cb185-1" tabindex="-1"></a><span class="fu">fisher.test</span>(<span class="fu">table</span>(df_1<span class="sc">$</span>sexL, df_1<span class="sc">$</span>traitL))</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  table(df_1$sexL, df_1$traitL)
## p-value = 0.4536
## alternative hypothesis: two.sided</code></pre>
<p>D’après le test exact de Fisher, on ne peut pas rejetter l’hypothèse nulle d’égalité de la répartition par sexe dans les 3 groupes de traitement.</p>
</div>
<div id="corrélations" class="section level3 hasAnchor" number="3.7.6">
<h3><span class="header-section-number">3.7.6</span> Corrélations<a href="#corr%C3%A9lations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On peut calculer les <strong>corrélations de Pearson et de Spearman</strong> entre la PAS et l’IMC avec la fonction <code>cor()</code>. La fonction <code>cor.test()</code> teste l’hypothèse nulle <span class="math inline">\(H0: \rho = 0\)</span> (elle recalcule également le coefficient de corrélation ainsi qu’un intervalle de confiance). Au sein de ces deux fonctions, vous pouvez préciser si vous souhaiter calculer et tester une corrélation de Pearson ou de Spearman avec l’argument <code>method</code>.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="analyse-simple-en-r-base.html#cb187-1" tabindex="-1"></a><span class="do">### Estimer puis tester une corrélation de Pearson entre PAS et IMC</span></span>
<span id="cb187-2"><a href="analyse-simple-en-r-base.html#cb187-2" tabindex="-1"></a>rho_pearson <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(df_1<span class="sc">$</span>imc, df_1<span class="sc">$</span>pas, <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>) </span>
<span id="cb187-3"><a href="analyse-simple-en-r-base.html#cb187-3" tabindex="-1"></a>rho_pearson</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  df_1$imc and df_1$pas
## t = 3.8534, df = 298, p-value = 0.0001427
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.1072647 0.3231284
## sample estimates:
##       cor 
## 0.2178593</code></pre>
<p>Le coefficient de corrélation de Pearson est <span class="math inline">\(\rho_1 = 0.218\)</span>, il est signficativement différent de 0 (p=0.00014).</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="analyse-simple-en-r-base.html#cb189-1" tabindex="-1"></a><span class="do">### Estimer puis tester une corrélation de Pearson entre PAS et IMC</span></span>
<span id="cb189-2"><a href="analyse-simple-en-r-base.html#cb189-2" tabindex="-1"></a>rho_spearm <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(df_1<span class="sc">$</span>imc, df_1<span class="sc">$</span>pas, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>) </span></code></pre></div>
<pre><code>## Warning in cor.test.default(df_1$imc, df_1$pas, method = &quot;spearman&quot;):
## Impossible de calculer la p-value exacte avec des ex-aequos</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="analyse-simple-en-r-base.html#cb191-1" tabindex="-1"></a>rho_spearm</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df_1$imc and df_1$pas
## S = 3522826, p-value = 0.0001503
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##      rho 
## 0.217141</code></pre>
<p>Le coefficient de corrélation de Spearmon est <span class="math inline">\(\rho_2 = 0.217\)</span>, il est signficativement différent de 0 (p=0.00015).</p>
</div>
</div>
<div id="analyse-multivariée" class="section level2 hasAnchor" number="3.8">
<h2><span class="header-section-number">3.8</span> Analyse multivariée<a href="#analyse-multivari%C3%A9e" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Nous allons estimer un modèle multivarié de la moyenne de pression artérielle systolique, en fonction du traitement, ajusté sur le sexe et l’IMC.</p>
<p>Pour cela nous allons utiliser la fonction <code>lm()</code> (<em>linear model</em>) :</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="analyse-simple-en-r-base.html#cb193-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(pas <span class="sc">~</span> traitL <span class="sc">+</span> sexL <span class="sc">+</span> imc, </span>
<span id="cb193-2"><a href="analyse-simple-en-r-base.html#cb193-2" tabindex="-1"></a>            <span class="at">data =</span> df_1)</span>
<span id="cb193-3"><a href="analyse-simple-en-r-base.html#cb193-3" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = pas ~ traitL + sexL + imc, data = df_1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.871 -10.083  -0.342  10.941  41.171 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        109.5668     7.1403  15.345  &lt; 2e-16 ***
## traitLTraitement A -10.9623     2.1246  -5.160 4.55e-07 ***
## traitLTraitement B  -2.8373     2.1374  -1.327 0.185388    
## sexLMasculin         8.5634     1.7796   4.812 2.39e-06 ***
## imc                  1.1240     0.2904   3.870 0.000134 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.24 on 295 degrees of freedom
## Multiple R-squared:  0.1902, Adjusted R-squared:  0.1792 
## F-statistic: 17.32 on 4 and 295 DF,  p-value: 8.911e-13</code></pre>
<p>Après ajustement sur le sexe et l’IMC, on observe que :</p>
<ul>
<li>la PAS était en moyenne inférieure de -11.0 mmHg dans le groupe traitement A par rapport au groupe placebo, de manière significative (p=4.6e-07),</li>
<li>la PAS était en moyenne inférieure de -2.8 mmHg dans le groupe traitement B par rapport au groupe placebo, de manière non-significative (p=0.19).</li>
</ul>
<p>Pour vérifier les conditions d’application, la méthode la plus classique est de représenter le nuage de points des résidus en fonction des valeurs prédites par le modèle. On peut se servir de l’opérateur dollar pour récupérer :</p>
<ul>
<li>les résidus du modèle <code>model$residuals</code></li>
<li>les valeurs prédites par le modèle <code>model$fitted.values</code></li>
</ul>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="analyse-simple-en-r-base.html#cb195-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)) <span class="co"># 1 figure sur 1 ligne et 1 colonne</span></span>
<span id="cb195-2"><a href="analyse-simple-en-r-base.html#cb195-2" tabindex="-1"></a></span>
<span id="cb195-3"><a href="analyse-simple-en-r-base.html#cb195-3" tabindex="-1"></a><span class="co"># la fonction suivant trace une courbe lissée (loess) </span></span>
<span id="cb195-4"><a href="analyse-simple-en-r-base.html#cb195-4" tabindex="-1"></a><span class="co"># au milieu d&#39;un nuage de points</span></span>
<span id="cb195-5"><a href="analyse-simple-en-r-base.html#cb195-5" tabindex="-1"></a><span class="fu">scatter.smooth</span>(model<span class="sc">$</span>fitted.values, model<span class="sc">$</span>residuals, </span>
<span id="cb195-6"><a href="analyse-simple-en-r-base.html#cb195-6" tabindex="-1"></a>               <span class="at">lpars =</span> <span class="fu">list</span>(<span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>, <span class="at">lty =</span> <span class="dv">1</span>), </span>
<span id="cb195-7"><a href="analyse-simple-en-r-base.html#cb195-7" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="st">&quot;Valeurs prédites&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Résidus&quot;</span>)</span>
<span id="cb195-8"><a href="analyse-simple-en-r-base.html#cb195-8" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="co"># ajoute une ligne horizontale en 0</span></span>
<span id="cb195-9"><a href="analyse-simple-en-r-base.html#cb195-9" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="fl">0.5</span>, <span class="co"># largeur de ligne (line width)</span></span>
<span id="cb195-10"><a href="analyse-simple-en-r-base.html#cb195-10" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">2</span>) <span class="co"># type de ligne = pointillé</span></span></code></pre></div>
<p><img src="_main_files/figure-html/multi2-1.png" width="672" /></p>
<p>De manière encore plus automatisée, la commande <code>plot(model)</code> permet d’obtenir une série de 4 graphiques de diagnostic post-estimation d’un modèle de régression linéaire (tapez la touche “entrée” 4 fois pour obtenir les graphiques) :</p>
<ul>
<li>le 1er graphique est le nuage de points des résidus en fonction des valeurs prédites</li>
<li>le 2ème graphique permet de vérifier la normalité des résidus standardisés</li>
<li>le 3ème graphique est le nuage de points de la racine carrée des résidus standardisés en fonction des valeurs prédites</li>
<li>le 4ème graphique le nuage de points des résidus standardisés en fonction des distances de Cook (pour évaluer l’effet levier)</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="les-objets-dans-r.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/benoitlepage/formationR/02-analyse_en_R_base.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
